### ISSUE TITLE
multi level bracket notation

### ISSUE THREAD

**Issue by zsitro** [sindresorhus/query-string#100]
Hi, how can I deal with situations like:

```
queryString.parse('?obj[child][prop1]=11&obj[child][prop2]=22')

//yield:
{
  "obj[child][prop1]":"11"
  "obj[child][prop2]":"22"
}

// instead:
{
  obj:{
    child: {
      prop1: "11"
      prop2: "22"
    }
  }
}
```

`arrayFormat: 'index'` doesn't help in this situation. Any help appreciated :) ty

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/query-string#nesting or use a different library.

**Comment by zsitro** [comment]
https://github.com/ljharb/qs  TJ ^^
