### ISSUE TITLE
ES6ify?

### ISSUE THREAD

**Issue by sudo-suhas** [sindresorhus/query-string#105]
Can I make a PR using ES6 features supported in node 4? Specifically, `() => {}`, `const`/`let` , `${template} strings`, `{ objectShorthands }` and `Object.assign`.

**Comment by SamVerschueren** [comment]
This is one of the few modules we don't ES2015ify because it's mainly used in browser based applications.

**Comment by sudo-suhas** [comment]
Alright. Thanks.

**Comment by marcodpt** [comment]
I create an alternative project if you want to use es6 module, with a very simple api:
[query](https://github.com/marcodpt/query)
