### ISSUE TITLE
Support 'all' option for arrayFormat

### ISSUE THREAD

**Issue by shanemcquillan** [sindresorhus/query-string#108]
You've created an awesome package here, thank you. I'm using it successfully in a project, but I've recently ran into an issue where different clients generate URLs with different arrayFormats for my service, so specifying the format for parsing is not flexible enough.

It would be awesome if you could extend query-string's parse method to support an 'all' option for arrayFormat. When that option's chosen, a function could iterate the query keys, and based on their format return what the arrayFormat is, which could be passed through to your existing code. If the url mixes and matches arrayFormats, it would raise an exception.

I'm open to sending you a PR for this, but passing it by you first in case you have any objections. I also figure you could add this considerably quicker than I could since you already know the codebase.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but not something I'm interested in adding.

**Comment by shanemcquillan** [comment]
Any particular reason? I don't see the downside apart from the extra code to maintain, which should be minimal given that it should really only be the addition of a function to figure out the format and some wiring.
