### ISSUE TITLE
queryString.parse doesn't ignore ? in location.search.

### ISSUE THREAD

**Issue by josephong** [sindresorhus/query-string#110]
On v5.0.0, passing in:

`?foo=bar`

Yields:

`{?foo: "bar"}`

**Comment by josephong** [comment]
Sorry, just saw that it had been fixed.

**Comment by josephong** [comment]
Nevermind, #109 addresses "extract" not working? According to the docs, parse needs to ignore ? as well.

```
.parse(string, [options])
Parse a query string into an object. Leading ? or # are ignored, so you can pass location.search or location.hash directly.
```

**Comment by josephong** [comment]
How is:

`https://github.com/sindresorhus/query-string/blob/f2833411bbe975d38b261ed46c96edde4bd0e6e7/test/parse.js#L4`

Not breaking?

**Comment by josephong** [comment]
Nevermind, issue with npm packages on my side. ;)

**Comment by apuntovanini** [comment]
@josephong how did you solve this? #109 was merged but I face the same issue...Thanks!

**Comment by MoiseScalzo** [comment]
I'm facing the same issue with react useLocation().search `?foo=bar` it return `{"?foo": "bar"}`

**Comment by rexebin** [comment]
@MoiseScalzo ditto here
