### ISSUE TITLE
No value?

### ISSUE THREAD

**Issue by kkashou** [sindresorhus/query-string#114]
Is there a way to say to ignore if a param has no value?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string#falsy-values

**Comment by kkashou** [comment]
What if you don’t know what they are ?

**Comment by BornaP** [comment]
@sindresorhus It would be nice to have option where you could supply falsy values that stringify won't include in params string (currently you have to set those values to undefined). If you agree on that, I can make PR for this.

**Comment by sindresorhus** [comment]
I’m not interested in more options.
