### ISSUE TITLE
Problem in encoding white space in query param value

### ISSUE THREAD

**Issue by vikasrohit** [sindresorhus/query-string#115]
If I have following object 
<pre>
var criteria = {
    "foo: "bar",
    "sort" : "updatedAt desc",
    "page": 1 
}
</pre>

And use following code to stringify it:

`querystring.stringify(criteria)`

it generates following output:

`page=1&sort=updatedAtNaNesc&foo=bar`

Is this a known issue or I am using the library in wrong way?

I have already tried passing options to the stringify method as follows:
`{ encode: true, strict: true}`

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.

**Comment by vikasrohit** [comment]
Makes sense. Would try to create failing test.
