### ISSUE TITLE
Make available on CDN.JS

### ISSUE THREAD

**Issue by htkoca** [sindresorhus/query-string#117]
I use this library quite a lot and it would be great if I could also leverage CDN.js's cloudflare enabled service as well.

**Comment by sindresorhus** [comment]
Feel free to do so. I don't use CDNJS or know how to add it there.

**Comment by htkoca** [comment]
Thanks - Here's the request https://github.com/cdnjs/cdnjs/issues/12348

**Comment by sufuf3** [comment]
@htkoca @sindresorhus Sorry for bother.
I am a member of CDNJS.
Would you mind telling me that which file can be used in web front-end?
I read `Usage` in README, I know this lib can be used in node.js.

I'm not sure that is this lib can be used as `<script src="index.js"></script>`.
Thank you very much.

cc @cy91244

cdnjs/cdnjs#12356
cdnjs/cdnjs#12348
cdnjs/cdnjs#10334
