### ISSUE TITLE
&amp; → & support

### ISSUE THREAD

**Issue by rogaldh** [sindresorhus/query-string#118]
Hello there.

There is an issue with `&amp;` queryString delimiters.
```
var queryString = require("query-string")
queryString.parse('?conf=test&amp;session=234d534cth&amp;token=348n57934yv6')
```
This case is awkward a bit but occurs sometimes.
I might make PR but is this stuff relevant?

Cheers.

**Comment by sindresorhus** [comment]
That’s an HTML escape and not related to query strings. It’s up to you to unescape it before passing it in here.

**Comment by rogaldh** [comment]
Ok, not a problem. You'll never know the way a user came to the site.
