### ISSUE TITLE
+ is parsed as white space

### ISSUE THREAD

**Issue by caddac** [sindresorhus/query-string#119]
I see there is a test that indicated `+` should be parsed into white space, however when I test this here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
`+` is encoded as `%2B`.

**Comment by sindresorhus** [comment]
https://stackoverflow.com/a/2678602/64949

**Comment by caddac** [comment]
Resolved by using encodeUriComponent to convert `+` into `%2B` in query strings.

**Comment by visualcookie** [comment]
Hey @caddac 

This did not work in my case. When doing
```js
const urlEncode = encodeURIComponent(location.search)
const urlParsed = query.parse(urlEncode)
```
it returns
![image](https://user-images.githubusercontent.com/1857554/58536561-3fdc1480-81f1-11e9-9e18-ae51e22ac5ba.png)

**Comment by Anusien** [comment]
Why does `query-string.parse()` still convert '+' into ' ' when the `decode` option is set to `false`? This isn't handled by `decode-uri-component` but it's [manually done via string manipulation](https://github.com/sindresorhus/query-string/blob/master/index.js#L209).

**Comment by Bijiabo** [comment]
> Why does `query-string.parse()` still convert '+' into ' ' when the `decode` option is set to `false`? This isn't handled by `decode-uri-component` but it's [manually done via string manipulation](https://github.com/sindresorhus/query-string/blob/master/index.js#L209).

In my use case, URL has a Base64 query string value, it will be wrong if the `+` convert to space automatically. Maybe I need to replace back to `+` for my Base64 query string.
