### ISSUE TITLE
Invalid result for named keys i.e. string inside square brackets

### ISSUE THREAD

**Issue by itaditya** [sindresorhus/query-string#120]
## Code
```js
query = '?foo[a]=1&foo[a]=2&foo[b]=3'
queryString.parse(query)
```
## Current Output

```js
 { 'foo[a]': [ '1', '2' ], 'foo[b]': '3' }
```

## Expected Output

```js
 {
   foo: {
         a: [ '1', '2' ], 
         b: '3' 
   }
 }
```

Is this intentional because in [line 88](https://github.com/sindresorhus/query-string/blob/master/test/parse.js#L88) you have a test which has something like this.

**Comment by sindresorhus** [comment]
There's also a test there that shows you exactly what you need: https://github.com/sindresorhus/query-string/blob/6404fd9dd2d59c8a775e2392e6703ea074b48894/test/parse.js#L115-L117

**Comment by itaditya** [comment]
Ok, I read the tests but there was nothing about object with named keys having arrays.

**Comment by sindresorhus** [comment]
Oh, I missed that the keys were named. That’s not supported, and won’t be. Check out https://www.npmjs.com/package/qs instead.

**Comment by itaditya** [comment]
oh ok thanks for the link :)
