### ISSUE TITLE
Error building minified bundle in react app

### ISSUE THREAD

**Issue by sbrichardson** [sindresorhus/query-string#126]
I received an error after updating to `query-string: v6.0.0`

I'm using it in a frontend app, based on `create-react-app` (react v16+ not ejected, chrome)

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/query-string/index.js:8

Read more here: http://bit.ly/2tRViJ9

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/releases/tag/v6.0.0

**Comment by joshuaalpuerto** [comment]
Have to revert back to `5.1.0` to make bundling with work

**Comment by jasononeil** [comment]
@sindresorhus would you be open to a PR that uses Babel to compile index.js to ES5 before packaging and submitting to NPM? 

This change breaks our use of query-string in a browser environment unless we change our webpack config to compile all node_modules JS files, which would slow down our build times dramatically. Having a babel-compiled version that is used in the NPM bundle would solve this issue for us, while allowing you to keep using the new features like `const` and arrow functions in the source file.

**Comment by sindresorhus** [comment]
[I am not.](https://github.com/sindresorhus/ama/issues/446) Just stay on version 5 if you need it. This module is mature and stable and will probably not change much.
