### ISSUE TITLE
Create-react-app failed to minify v6

### ISSUE THREAD

**Issue by Stupidism** [sindresorhus/query-string#127]
```

Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file: 
 	./node_modules/query-string/index.js:8 
Read more here: http://bit.ly/2tRViJ9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! huskar@0.6.3 build: `react-app-rewired build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the huskar@0.6.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-03-14T10_27_43_189Z-debug.log
```

**Comment by Stupidism** [comment]
As the [link](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) CRA put in the error message recommended, I open a issue here.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

Also, see the [release notes of v6](https://github.com/sindresorhus/query-string/releases/tag/v6.0.0).

**Comment by sindresorhus** [comment]
Stay on version 5 if you need to use this with Create React App.
