### ISSUE TITLE
[Object, Object]

### ISSUE THREAD

**Issue by FDiskas** [sindresorhus/query-string#128]
Stringify function returns wrong response
https://runkit.com/fdiskas/5aa958a896e0dd0012ae7b2a

**Comment by FDiskas** [comment]
if object is empty the parameter should be removed. :european_castle:

**Comment by sindresorhus** [comment]
This module only supports primitive values as object values.

**Comment by FDiskas** [comment]
what about https://github.com/sindresorhus/query-string#falsy-values
looks like similar for me

**Comment by SamVerschueren** [comment]
It's explained in the [Nesting section](https://github.com/sindresorhus/query-string#nesting).

**Comment by FDiskas** [comment]
then it is useless :cry: 
```js
const queryString = require('query-string');
const parsed = {
    pageNumber: 1,
    inPage: 5,
    sortField: "default",
    sortDirection: "asc",
    filter: {
        foo: 'baz'
    }
};
const stringified = queryString.stringify(parsed);
// returns: "filter=%5Bobject%20Object%5D&inPage=5&pageNumber=1&sortDirection=asc&sortField=default"
```
For other that will land to the same issue - use [qs](https://www.npmjs.com/package/qs) module
```js
const queryString = require('qs');
const parsed = {
    pageNumber: 1,
    inPage: 5,
    sortField: "default",
    sortDirection: "asc",
    filter: {
        foo: 'baz'
    }
};
const stringified = queryString.stringify(parsed);
// returns: "pageNumber=1&inPage=5&sortField=default&sortDirection=asc&filter%5Bfoo%5D=baz"
```
