### ISSUE TITLE
MInification error when used with create-react-app

### ISSUE THREAD

**Issue by yuchuan1** [sindresorhus/query-string#129]
After upgrading to 6.0.0, when I type 'yarn run build' command to create production build, it shows the following error

$react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/query-string/index.js:8

Read more here: http://bit.ly/2tRViJ9

error An unexpected error occurred: "Command failed.
Exit code: 1

**Comment by SamVerschueren** [comment]
Duplicate #126 & #127
