### ISSUE TITLE
Breaks in Firefox

### ISSUE THREAD

**Issue by dcousens** [sindresorhus/query-string#13]
Thanks to https://bugzilla.mozilla.org/show_bug.cgi?id=483304, this module breaks if you use `window.location.hash` directly.

It's not really your fault, but, it is important to note this module is unsafe to use in the suggested way.

Perhaps check if the `decodeURIComponent` actually changes anything first, and if it doesn't, assume it is already decoded?

**edit:** For that to work though you'd have to stipulate (pre-decoded) base 64 keys would be unsafe (as you'd only be able to split on the first `=`)

**edit2:** Or just suggest [this](https://stackoverflow.com/questions/4835784/firefox-automatically-decoding-encoded-parameter-in-url-does-not-happen-in-ie)

**Comment by nobitagit** [comment]
This bug has recently been fixed (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=483304) and [here](https://bugzilla.mozilla.org/show_activity.cgi?id=483304)), and now the module works out of the box in FF too, so I guess that the warning in the readme can be removed.
