### ISSUE TITLE
"Invalid assignment" error after upgrading to version 6.0.0

### ISSUE THREAD

**Issue by kaiyoma** [sindresorhus/query-string#134]
If I upgrade to 6.0.0 (from 5.1.0) and run my normal webpack build, it fails with this error:

```
ERROR in dependencies.bundle.36418d77caa7c4dab512.js from UglifyJs
Invalid assignment [./node_modules/query-string/index.js:8,0][dependencies.bundle.36418d77caa7c4dab512.js:166154,30]
```

**Comment by sindresorhus** [comment]
Looks like you need to upgrade UglifyJS to the latest version that supports ES6 syntax, or transpile your dependencies.

**Comment by ahmetkuslular** [comment]
Same problem; upgrade to 6.10.1 from 5.1.1.

`Compilation bundle error occurred
[
  'vendors~client-489e004695193532001e.js from UglifyJs\n' +
    'Unexpected token: keyword «const» [vendors~client-489e004695193532001e.js:30397,0]'
]
`

i'am using;
webpack@4.41.2
uglifyjs-webpack-plugin@2.2.0
