### ISSUE TITLE
add method to get query string from url

### ISSUE THREAD

**Issue by WickyNilliams** [sindresorhus/query-string#15]
For convenience, it would be nice to have a method that can pluck the query string from a url:

```js
var qs = require("query-string");
var url = "http://some.url/with?a=few&query=params";
var query = qs.getQuery(url); // "?a=few&query=params"
qs.parse(query); // { a : "few", query : "params" }
```

**Comment by WickyNilliams** [comment]
perhaps a little naive, but implementation could be as simple as this?

```js
function getQuery(url) {
   return (url || "").split(/[\?\#]/)[1];
}
```

**Comment by sindresorhus** [comment]
Why? Use `url.parse` in Node or `location.search` in the browser.

And yeah that implementation is too naive. Look at something like http://medialize.github.io/URI.js/ for how to do it correctly.

**Comment by WickyNilliams** [comment]
I guess i was just a little surprised that it wouldn't query parse when given the full URL, and doesn't have a way to extract query string. I'm working in the browser, not parsing the current URL (so location.search isn't useful) but strings containing URLs.

Their implementation seems just as naive tbh, split on "?" https://github.com/medialize/URI.js/blob/891b5551da274d1ef3ff23ad3fdabea2b98344fd/src/URI.js#L406-L411

**Comment by WickyNilliams** [comment]
I suppose I could:

```js
function getQuery(url) {
  var anchor = document.createElement("a");
  anchor.href = url;
  return anchor.search;
}
```

but that's a bit nasty imo

**Comment by sindresorhus** [comment]
Not sure if it matters, but URI.js removes the fragment (`#`) before searching for the querystring `?`.

PR welcome :)

**Comment by kud** [comment]
+1 for this.

I receive an url in a json content, and I had to do `response.url.split('?')[1]`.

**Comment by adam-lynch** [comment]
+1

**Comment by skibz** [comment]
+1

**Comment by sindresorhus** [comment]
The next `+1` automatically volunteers to do a pull request ;)

**Comment by kud** [comment]
+2

**Comment by sindresorhus** [comment]
@kud I'll be expecting a pull request shortly.

**Comment by kud** [comment]
rofl ;)

To be honest, I could work on it because I'm interested. I note it my (never) todo list.

**Comment by skibz** [comment]
with pleasure

**Comment by WickyNilliams** [comment]
@sindresorhus happy to take a look at this, being the person that created the issue and thus the plus-1-storm :D 

You would like it handled transparently by the parse method? Personally I'd go for an extra method (explicit > implicit, and doesn't change existing behaviour!), but it's your call ultimately :)

**Comment by sindresorhus** [comment]
@WickyNilliams I generally agree with explicitness, but since this can be done without any downsides I don't see why we couldn't just handle this automagically. I'm fine with exposing the method too though, in case you only need to extract it for some reason. Method should be named `.extract()` unless anyone can come up with a better name.

**Comment by xspirkovska** [comment]
I was also trying to get query string from a url:

define(['query-string'], function (qs) {
...
    getQueryParams: function (url) {
         var queryParams = {
	    url: qs.parse(url.split('?')[1]),
        };
...
});
 

It's working fine in Chrome, Firefox and IE 9+, however an error displays when I try it in IE8 (tested on Win7):

Message: Object doesn't support this property or method (line 17, character 3) 

line 17 in query-string.js => str = str.trim().replace(/^(\?|#)/, '');

IE8 doesn't support it, so I was wondering if it's possible to 'enhance' the current functionality and make it work in IE8? :)  

(http://stackoverflow.com/questions/11219731/trim-function-doesnt-work-in-ie8)

**Comment by filipisiqueira-luizalabs** [comment]
Hi,

Have somebody working in this feature?

@xspirkovska, I think you need to open a new issue to enhance this functionality.

**Comment by WickyNilliams** [comment]
I took a quick look at submitting a PR finally for this. Overall code is pretty simple, but to handle it seamlessly in the background has one small tricky part, that i'm not sure how best to work around...

If it's handled transparently by parse then there are 3 possible inputs:
* a query string (as has always been the case)
* a url containing a query string (new possible input, easily parsed by splitting on `'?'`)
* a url without a query string (new possible input, difficult to detect)

It is the last item which proves tricky. See this rough sketch of the getQueryString method:

```js
queryString.getQueryString = function (maybeUrl) {
  if(!maybeUrl) {
    return;
  }

  var pos = maybeUrl.indexOf('?');
  if(pos > -1) {
    return maybeUrl.substring(pos + 1);
  }

  // assume it was already a query string (or a URL without query string!)
  return maybeUrl;
};
```

Imagine the following tests for parse:

```js
it('should handle full URLs', function() {
  assert.deepEqual(qs.parse("http://foo.bar/?abc=def&hij=klm"), { abc : "def", hij : "klm" });
  assert.deepEqual(qs.parse("http://foo.bar/?"), {});
  assert.deepEqual(qs.parse("http://foo.bar"), {});
});
```

The third assert fails because getQueryString assumes lack of `'?'` means it's treated as already being a query string, and you get back `{"http://foo.bar":null}` instead of `{}`

This is why I thought explicitly calling `getQueryString` is a better option for the user. They are more likely to know what shape of their data, and act accordingly. We don't have to jump through hoops behind the scenes to determine if URL or not. 

Unless I'm just being stupid and there's an obvious way to handle this??

**Comment by sindresorhus** [comment]
The only way you can differentiate is the protocol `/\w+:\/\//.test(str)`.

**Comment by WickyNilliams** [comment]
Do we want to be doing that? I worry there will be edge-cases galore. For example, that particular regex would fail protocol-relative URLs

**Comment by sindresorhus** [comment]
Yeah, I agree. Better to be explicit.
