### ISSUE TITLE
IE8 and String.prototype.trim

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/query-string#16]
(I know, I know) Unfortunately we have to support IE8 for a little while longer over here. String.prototype.trim isn't a thing in IE8. While I dislike munging with prototypes of native classes, this would be a simple addition:

```
if (!String.prototype.trim) {
  (function() {
    // Make sure we trim BOM and NBSP
    var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
    String.prototype.trim = function() {
      return this.replace(rtrim, '');
    };
  })();
}
```

Or alternatively, making that a private scope function would work as well.

**Comment by sindresorhus** [comment]
You're free to add whatever shims you want yourself, but I stopped caring about IE8 years ago and won't add bloat to support it, sorry.

https://cdn.polyfill.io/v1/docs/ maybe.

**Comment by shellscape** [comment]
Fair enough (I wish I could say the same!)

I'd say it would be prudent to update the readme with that tidbit though ;)
