### ISSUE TITLE
Any breaking changes from 5 to 6?

### ISSUE THREAD

**Issue by terencechow** [sindresorhus/query-string#175]
I'd like to upgrade from v5 to v6 but I'm not aware if there are any breaking changes. Can you share what changes might break as a result? 

I'm not too concerned with browser support on older browsers or using create-react-app v1. I'm more concerned about what specific things may have broken from v5 to v6. Thanks!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/releases/tag/v6.0.0

**Comment by terencechow** [comment]
Thanks, I did read that, but I just wanted to make sure that there are no breaking changes besides that.
