### ISSUE TITLE
nested query label:question

### ISSUE THREAD

**Issue by Candore** [sindresorhus/query-string#178]
I have an input query json that looks like this,

```
query: {
 fruits : ['apple'],
 vegetables: JSON.stringify({
            name: 'carrot',
            color:"orange",
          }),
}
```

And I like my url to like this

**www.baseurl.com/?fruits=apple&vegetables.name=carror&vegetables.color=orange**

May I know how I can form this ?

I tried `console.log(queryString.stringify(query));`, but it came out like this instead,
`fruits=apple&vegetables=%7B%name%22%3A%carrot%22%2C%22color%22%3A%22orange%22%7D`

**Comment by sindresorhus** [comment]
I think you can achieve that with https://github.com/ljharb/qs
