### ISSUE TITLE
Add parseBooleans option

### ISSUE THREAD

**Issue by felixoi** [sindresorhus/query-string#182]
Parsing an object like 
```javascript
{
    test: true
}
```
results in `test=true`. Using stringify it results in
```javascript
{
    test: "true"
}
```

That's why I think we need an additional option like parseNumbers for booleans.

**Comment by sindresorhus** [comment]
Sure. PR welcome. Should be off by default.

You can see how `parseNumbers` was added for inspiration: https://github.com/sindresorhus/query-string/commit/f7be8318e455ba67482d7a501dd1311194f96b89
