### ISSUE TITLE
broken types for `parse`

### ISSUE THREAD

**Issue by alecf** [sindresorhus/query-string#184]
by adding `|number` to the value side of ParsedQuery, you've changed the return type in a really breaking the type signature for users who don't use `parseNumbers` - now every use of this generates errors like this:
```
[devserver] TS2345: Argument of type 'string | number | ReactText[]' is not assignable to parameter of type 'string | string[]'.
[devserver]   Type 'number' is not assignable to type 'string | string[]'.
```
This is only going to get worse when #183 is fixed.

I'd like to suggest either a complex typescript signature such that only passing `parseNumbers` results in the new `string |number| (number|string)[]`, or introduce a new  function `parseValues` which does the number/boolean/etc

**Comment by danilofuchs** [comment]
The first option seems better: 
Have a complex type signature that changes output type depending on config.
This could also be applied to arrays, maybe only if you pass `parseArray` option, it could return an Array

**Comment by sindresorhus** [comment]
> I'd like to suggest either a complex typescript signature such that only passing parseNumbers results in the new string |number| (number|string)[]

👍 PR welcome :)

**Comment by felixoi** [comment]
Is someone with Typescript knowledge working on this? I'd like to fix it but I've kinda so knowledge of Typescript.
