### ISSUE TITLE
New query parameter gets added in the beginning of the search string instead of end (appending)

### ISSUE THREAD

**Issue by ashishsanjayrao** [sindresorhus/query-string#188]
I'm trying to add a new query parameter to an existing string of parameters. What I was expecting is that the new parameters get appended instead of prepended.

Here's my code:
```
parsed = queryString.parse(this.props.location.search);
parsed.duration = value;
newSearch = queryString.stringify(parsed);
```
And that gives me: `?duration=2&location_id=3` instead of `?location_id=3&duration=2`

Is there any way we can append instead of prepend?

Thanks!

**Comment by sindresorhus** [comment]
You can turn off sorting with the `sort` option.
