### ISSUE TITLE
SCRIPT1002: Syntax error on IE11 in ver ^6.0

### ISSUE THREAD

**Issue by iainheng** [sindresorhus/query-string#189]
I am using webpack and upgrading this library to latest version (as of now ver 6.8.1) is giving me Syntax Error in IE11 (other browsers are fine)

![image](https://user-images.githubusercontent.com/3263759/60169195-d32c5800-9838-11e9-9ab2-66f764193046.png)

And this is the exact error location:
![query-string-ie11](https://user-images.githubusercontent.com/3263759/60169231-e3dcce00-9838-11e9-8bbc-bb3d3917e5c4.jpg)

Downgrading to version 5 does not trigger this error. 

Any help or fix is very much appreciated on this.

**Comment by sindresorhus** [comment]
From the top of the readme:

> This module targets Node.js 6 or later and the latest version of Chrome, Firefox, and Safari. If you want support for older browsers, or, if your project is using create-react-app v1, use version 5: npm install query-string@5.

**Comment by dpistoleKUBRA** [comment]
This one bit us in prod, ty @iainheng for opening issue it made finding the resolution quick enough.

I wonder if theres a reason for not transpiling down to support older browsers? I don't think IE11 is EOL yet 🤔 anyway thanks for the package.

**Comment by ChuckJonas** [comment]
Same thing... This has tripped me up on two separate occasions now (shame on me).  Given the simplicity of this library, seems like no reason not to target something lower.

**Comment by margaritacoco** [comment]
So what is the "real" solution to fix this?

**Comment by ewief** [comment]
I guess it is possible to just parse it on build using `babel-loader`
```
        test: /\.js$/,
        exclude: /node_modules[\\,/](?!(query-string)[\\,/]).*/,
        use: {
          loader: 'babel-loader',
        }
```
or im I wrong?

**Comment by abhimna** [comment]
> From the top of the readme:
> 
> > This module targets Node.js 6 or later and the latest version of Chrome, Firefox, and Safari. If you want support for older browsers, or, if your project is using create-react-app v1, use version 5: npm install query-string@5.

v5 does not support custom decode options. With v6, we can just use
querystring.parse(data, {decode: false})
