### ISSUE TITLE
[Question] Advantages?

### ISSUE THREAD

**Issue by kud** [sindresorhus/query-string#190]
Hello,

I have a naive question about this project.

I'm currently writing (another) json:api client and I must write some urls to do it. I want to treat myself by using some libs to ease the writing of this client and I would like to know the advantages of this lib, compared to URLSearchParams?

Could you tell me what this lib gives more?

Thank you very much.

**Comment by sindresorhus** [comment]
Note that this module was made long before `URLSearchParams` was a thing.

Some benefits of using this module:
- It only needs transpilation work in older browser, not polyfills. To be able to use `URLSearchParams` in older browsers, you need to polyfill that API.
- It's very configurable. Query strings are not standardized, so servers use different incompatible formats. This module supports it all. `URLSearchParams` only supports one variant.

**Comment by kud** [comment]
That's sweet of you to answer so quickly.

Yes indeed, I used to use your lib for ages, and liked it! I understand that URLSearchParams didn't exist when you did it.

That's understood for the benefits, thank you!
