### ISSUE TITLE
parse() result returns object with null prototype

### ISSUE THREAD

**Issue by atassis** [sindresorhus/query-string#191]
It is a bad practice to create null prototype objects except rare cases. Library consumers have to set prototype by their own, this is an unnecessary behaviour.

**Comment by sindresorhus** [comment]
That's incorrect. It's actually an anti-pattern to **rely** on the object prototype being there: https://eslint.org/docs/rules/no-prototype-builtins

**Comment by atassis** [comment]
I know about the anti-pattern, but still the thing you do with an object is an undocumented behaviour. I got the mistake in another library, which calls an inherited method. I'll admit, it is wrong to use both `Object.create(null)` and `variable.hasOwnProperty`.
Since all inherited method are not enumerable, it is ok to use simple object notation here (`{}`). You even receive no perfomance gain, but an opposite https://jsperf.com/object-create-null-vs-literal/2

**Comment by atassis** [comment]
In [qs](https://www.npmjs.com/package/qs#parsing-objects) null prototype object can be generated via optional parameter

**Comment by Stinobe** [comment]
It would be useful if you could change it in the options somewhere.
I used the spread operator to fix it for now
`{ ...qs.parse(window.location.search) }`

**Comment by atassis** [comment]
@Stinobe i can advise you to use a `qs` module. It does all the things properly and has a wide set of options, like opted off by default null prototype.

**Comment by maotingyuan** [comment]
@Stinobe That's useful, thank you!
