### ISSUE TITLE
parse does not ignore leading '?' 

### ISSUE THREAD

**Issue by TheSolly** [sindresorhus/query-string#192]
Using parse on this
`"?openedFrom=/internal/store?rank=1&searchID=e7f1131f-90b8-47fc-a01c-04984b32fedb"
`
return only
`{searchID}` while expecting `{rank , searchID}`

And even removing the leading `?` and parse it
`"openedFrom=/internal/store?rank=1&searchID=e7f1131f-90b8-47fc-a01c-04984b32fedb"` 

return 
`{openedForm, searchID}` and totally ignoring `rank`

Using latest version as of writing this "query-string": "^6.8.1"

**Comment by sindresorhus** [comment]
You have to escape the second `?`.

The browser API works like this too.

`query-string`:

```js
queryString.parse('?openedFrom=/internal/store?rank=1&searchID=e7f1131f-90b8-47fc-a01c-04984b32fedb');
//=> {openedFrom: '/internal/store?rank=1', searchID: 'e7f1131f-90b8-47fc-a01c-04984b32fedb'}
```

Browser API:

```js
[...new URLSearchParams('?openedFrom=/internal/store?rank=1&searchID=e7f1131f-90b8-47fc-a01c-04984b32fedb')]
//=> [["openedFrom", "/internal/store?rank=1"], ["searchID", "e7f1131f-90b8-47fc-a01c-04984b32fedb"]]
```

**Comment by TheSolly** [comment]
@sindresorhus Understood, thanks for clarifying.
