### ISSUE TITLE
Typings for v5

### ISSUE THREAD

**Issue by nick-michael** [sindresorhus/query-string#193]
After having issues running on legacy devices we downgraded from v6 to v5 for browser compatibility which fixed our issues, but typescript typings do not exist in v5 so we needed to add the `d.ts` file manually.

Are these something that could be added to the v5 release?

**Comment by sindresorhus** [comment]
You can get the types for v5 with `npm i @types/query-string@5`. v5 is not going to change.

**Comment by nick-michael** [comment]
Interesting, I tried `@types/query-string` and got the error saying the types had moved within the package. Didn't think to specifically try `@5` - thanks
