### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by lienbcn** [sindresorhus/query-string#20]
Why this new version is only for nodejs and not included for browsers. It broke my app when I bower updated the dependencies.

**Comment by sindresorhus** [comment]
It's explained in the commit if you had bothered to take a look, and why it was a major release ;)
https://github.com/sindresorhus/query-string/commit/a4a45c12f76e4c727930f012e036319ae6c452cb

Just stay on 1.0.0 if you don't want to use browserify.

**Comment by Zhouzi** [comment]
Thanks for bringing this to the browser! For those who are interested, I created a fork with an UMD compatible version: [wizbii/query-string](https://github.com/wizbii/query-string)
