### ISSUE TITLE
New feature : Option to add leading "?"

### ISSUE THREAD

**Issue by nitinsh99** [sindresorhus/query-string#205]
Would you be open to PR for adding following option?

Example:

```
let params = {
"foo": bar
}
const url = `http://abc.com/xyz${stringify(params,{separator:true}})`
//prints http://abc.com/xyz?foo=bar

```

with falsy params
```
let params = undefined;
const url = `http://abc.com/xyz${stringify(params,{seperator:true})`
//prints http://abc.com/xyz
```

Rationale:
Avoid ternary checks like this everywhere:

`const url = params?  'http://abc.com/xyz?${stringify(params)' :  'http://abc.com/xyz'`

**Comment by sindresorhus** [comment]
I think it would be better to add a method that does the inverse of [`.parseUrl()`](https://github.com/sindresorhus/query-string#parseurlstring-options).

**Comment by afilp** [comment]
+1

I had exactly the same use case: Avoid using ternaries.

**Comment by komcal** [comment]
@sindresorhus Can I try to fix this? I'm thinking of creating a method named `parseObject` that you parse result of   [`.parseUrl`](https://github.com/sindresorhus/query-string#parseurlstring-options) to receive new url
### Example
```
const obj = {url: 'https://foo.bar', query: {foo: 'bar'}}
queryString.parseObject(obj)
//=> 'https://foo.bar?foo=bar'
```

**Comment by sindresorhus** [comment]
@komcal Sure.`parseObject` is not a good name. You don't parse an object. The name should be `stringifyUrl`.

**Comment by komcal** [comment]
```
const obj = {url: 'https://foo.bar', query: {foo: 'bar'}}
queryString.stringifyUrl(obj)
//=> 'https://foo.bar?foo=bar'
```
@sindresorhus Is this ok?

**Comment by sindresorhus** [comment]
Yes

**Comment by imaegoo** [comment]
+1

My case:
``` js
const obj = {url: 'https://foo.bar', query: {foo: ['bar', 'baz']}}
const options = {arrayFormat: 'bracket'}
queryString.stringifyUrl(obj, options)
//=> 'https://foo.bar?foo[]=bar&foo[]=baz'
```
