### ISSUE TITLE
Support predefining types

### ISSUE THREAD

**Issue by goodwin64** [sindresorhus/query-string#210]
(related to https://github.com/sindresorhus/query-string/issues/201)

## Consider 2 examples:

```ts
const search1 = '?phoneNumber=%2B380951234567&subtopicId=2&topicId=1';
const result1 = queryString.parse(search, {
  parseBooleans: true,
  parseNumbers: true,
});

const search2 = '?phoneNumber=a%2B380951234567&subtopicId=2&topicId=1';
const result2 = queryString.parse(search, {
  parseBooleans: true,
  parseNumbers: true,
});

console.log('result1', result1);
// {
//   phoneNumber: 380951234567,
//   subtopicId: 2,
//   topicId: 1,
// };
console.log('result2', result2);
// {
//   phoneNumber: 'a+380951234567',
//   subtopicId: 2,
//   topicId: 1,
// };
```

In the 1st example, "+" sign (`%2B` escaped) is ignored thus reducing to the number parsing, which is not what it supposed to be.

The main goal is to keep parsing numbers for parameters which values **starts** on the number and parse as plain string **otherwise**.

Does it look feasible to make a PR on this or should I not use `parseNumbers` option in that case?

**Comment by sindresorhus** [comment]
`+380951234567` is a valid number though. You would expect `'-380951234567'` to be parsed as a number, right? That being said, I agree it's not a optimal behavior.

// @yaodingyd

**Comment by yaodingyd** [comment]
What should be the optimal behavior? Here it's using Number() function to convert to number.

**Comment by goodwin64** [comment]
I meant if I store the number "+123" in the URL and then I parse it with "parseNumbers" option I get lost the plus sign (+) and the parsed value will be just "123".

Meanwhile I want to store some number-like parameters in URL so removing the "parseNumbers" option is not the right solution for me.

**Comment by goodwin64** [comment]
So when I prepend the value with the prefix "a" it's just a workaround not to lost the plus sign :)

"a+123" get parsed as is and then I just skip the "a" letter

**Comment by sindresorhus** [comment]
I think some kinda schema support here could solve the ambiguity. You could then explicitly define the type for this one key.  See: https://github.com/sindresorhus/query-string/issues/228#issuecomment-575197530

**Comment by iagolaguna** [comment]
Hi, I would like to help you to solve this issue, I was thinking about you said about schema.

What do you think about something like this

```
const search2 = '?phoneNumber=a%2B380951234567&subtopicId=2&topicId=1';
const result2 = queryString.parse(search, {
    parseBooleans: true,
    parseNumbers: true,
    schema: {
        phoneNumber: String, // StringConstructor
    }
});

````
and when you are trying to parse always check the schema and see if have a property with the same name of the URL param, with this you will be able to parse correctly any primitive type

**Comment by sindresorhus** [comment]
I would prefer something like this:

```js
const search2 = '?phoneNumber=a%2B380951234567&subtopicId=2&topicId=1';
const result2 = queryString.parse(search, {
    parseBooleans: true,
    parseNumbers: true,
    types: {
        phoneNumber: 'string',
        subtopicId: value => Number(value)
    }
});
```

The type could also be a function to let the user handle the converting it from a string to a custom type. Don't forget that it also needs to be able to handle arrays.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the feedback given in https://github.com/sindresorhus/query-string/pull/249.
