### ISSUE TITLE
Error: It is not being removed "?"

### ISSUE THREAD

**Issue by anthonywebster** [sindresorhus/query-string#218]
i am using the version 6.8.3, but does not remove symbol  **"?"**

![image](https://user-images.githubusercontent.com/3496319/67454301-f7c9ee00-f5e6-11e9-85e8-d52fd05f1373.png)

**Comment by sindresorhus** [comment]
// @yaodingyd

**Comment by yaodingyd** [comment]
I can't reproduce
https://codesandbox.io/s/red-feather-w2jn8

**Comment by anthonywebster** [comment]
Hi @yaodingyd , thank you very much for your prompt response. I did it as you did in the example and it works very well. The problem is if I do it as it is in the documentation.

This way it didn't work for me: **import queryString from "queryString"**.

but how do you do it if it works, thank you very much, why do you think it doesn't work the other way?

**Comment by yaodingyd** [comment]
it still works https://w2jn8.csb.app/?foo=bar
You can change the query string to anything.

Can you provide a link where it doesn't work?

**Comment by anthonywebster** [comment]
Ready, I found the error, everything goes very well with the package, thank you very much for your help @yaodingyd
