### ISSUE TITLE
Support hash

### ISSUE THREAD

**Issue by projct1** [sindresorhus/query-string#220]
```javascript
queryString.parseUrl('https://www.omg.com/page#param1&param2');
```
Result without hash...
```javascript
{​
    query: Object {  }
​    url: "https://www.omg.com/page"
}
```

**Comment by sindresorhus** [comment]
That's not currently supported. This is about query strings after all. That being said, I'm willing to merge a high-quality PR adding support for this. (Needs to add tests, docs, index.d.ts update).
