### ISSUE TITLE
Add `pipe` format to the `arrayFormat` option 

### ISSUE THREAD

**Issue by rikjacobs1390** [sindresorhus/query-string#226]
Lovely package! Thanks for the great work!
However, I'd love to have the option to split multiple values with the pipe ("|") operator without being URL encoded! 

**For example:**: 
/some/url?someParamGroup=10|20|30|40?someOtherParamGrou=string|some-other-string

This format is mainly used to shorten URLs which include things as identifiers, where there is expected to be a lot of them. It's a lot more readable!

Thanks in advance!

**Comment by sindresorhus** [comment]
I don't think this use-case is common enough to deserve adding yet another `arrayFormat` type. However, maybe you could come up with a more generic hook that would let you support your use-case and other future advanced use-cases.

**Comment by jpoehnelt** [comment]
I have this same request for pipe support. What about adding a case such as this? Could keep the 'comma' case and just fall through after setting `arrayFormatSeparator = ","`

``` 
arrayFormat: 'separator',
arrayFormatSeparator: "|"
```

Suggestions on names? I'll submit a pr.
