### ISSUE TITLE
Empty key triggers error in decode-uri-component

### ISSUE THREAD

**Issue by ianwensink** [sindresorhus/query-string#227]
When you have a query like `?foo=bar&baz`, `baz` won't have a value.

When the values get decoded with `decode-uri-component`, an error will be thrown:
> TypeError: Expected `encodedURI` to be of type `string`, got `undefined`

I think a check should be performed before decoding the value the prevent this error.

**Comment by sindresorhus** [comment]
We already have a test for this: https://github.com/sindresorhus/query-string/blob/cca729511b8ee4244caab51b7fce2c2a39775dc7/test/parse.js#L59-L62

Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look.
