### ISSUE TITLE
Not working on Chromium  v44 "Uncaught SyntaxError: Unexpected token =>" arrow functions

### ISSUE THREAD

**Issue by cbdeveloper** [sindresorhus/query-string#239]
Hello there,

I got this error on a "Samsung Internet v4", which uses Chromium v44.

So I downloaded the Chromium Version 44.0.2386.0 following [these instructions](https://www.chromium.org/getting-involved/download-chromium) and it seems that there's an error related to this package `query-string`.

![image](https://user-images.githubusercontent.com/43407798/74043032-890b7780-49c0-11ea-8e8e-994a87a2d641.png)

What could this be? Maybe an arrow function that wasn't transpiled?

I transpile my code using `babel`, but I usually only do it for my own `src` folder. Should I be transpiling this package to ES5 before use?

Thanks.

```
{
  test: /\.js$/,  
  include: path.resolve(__dirname, 'src'),
  use: ['babel-loader']
},
```

![image](https://user-images.githubusercontent.com/43407798/74045080-100e1f00-49c4-11ea-9ccb-081dd7b3c133.png)

Screen from my `node_modules` folder:

**stric-uri-encode:**

![image](https://user-images.githubusercontent.com/43407798/74044740-78103580-49c3-11ea-910f-98fce5a6c782.png)

**split-on-first**

![image](https://user-images.githubusercontent.com/43407798/74044843-a7bf3d80-49c3-11ea-8384-b5378c876c3c.png)

**query-string**

![image](https://user-images.githubusercontent.com/43407798/74044896-c1f91b80-49c3-11ea-8ac9-1ac34124d217.png)

**Comment by sindresorhus** [comment]
Sorry, I have no intention of supporting such an old version of Chromium.

You can either transpile this yourself or (from the readme):

> This module targets Node.js 6 or later and the latest version of Chrome, Firefox, and Safari. If you want support for older browsers, or, if your project is using create-react-app v1, use version 5: npm install query-string@5.

**Comment by seanblonien** [comment]
@sindresorhus Does query-string@5 support Typescript definition? 
My team and I recently updated to query-string 6.13.1 to fix Typescripts compile errors, but now we realize we need the backward compatibility of v5. Is there a way to use v5 and use Typescript definitions?
