### ISSUE TITLE
stringifyUrl is not a function

### ISSUE THREAD

**Issue by utazabanje** [sindresorhus/query-string#240]
Hello, I have an issue with stringifyUrl error. I couldn't find info about this anywhere so that's the reason i'm posting here.

<img width="703" alt="Screen Shot 2020-02-17 at 12 57 18 PM" src="https://user-images.githubusercontent.com/25405661/74651935-3f234e00-5185-11ea-9a8c-85887b788a2b.png">

So this is a piece of code i'm trying to implement and in gives me this error. It is imported in this file like 
`import queryString from 'query-string'`

![Screen Shot 2020-02-17 at 12 57 08 PM](https://user-images.githubusercontent.com/25405661/74651972-53ffe180-5185-11ea-81ee-7acb1285f0ec.png)

The strange thing about this is when i paste the same code into online editor it all works as expected.

Version of query-string is '6.11.0'.

Thanks

**Comment by baile320** [comment]
You might want to check your webpack settings. Mine works successfully with the bare minimum:

package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "query-string": "^6.11.0",
    "webpack-cli": "^3.3.11",
    "webpack": "^4.41.6"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

index.js
```
import queryString from 'query-string';
console.log(queryString.stringifyUrl({url: 'https://foo2.bar', query: {foo: 'bar'}}));
```

test.html
```
<head>
  <script src="./dist/main.js">
  </script>
</head>
```

built index.js -> ./dist/main.js using `npx webpack`. opening test.html logs `https://foo2.bar?foo=bar` as expected

**Comment by mattdell** [comment]
Are you using TypeScript? I'm having an issue where `stringifyUrl` isn't defined in the type definitions.

**Comment by DDushkin** [comment]
Same problem using CRA

**Comment by js2me** [comment]
Does anyone know previous versions have this problem ?

**Comment by js2me** [comment]
Just fixed it after:  
```
rm -rf node_modules
npm i
```

**Comment by js2me** [comment]
@mattdell try to install latest `@types/query-string` dev dependency

**Comment by sindresorhus** [comment]
> try to install latest @types/query-string dev dependency

This package ships with its own type definitions. You should not use `@types/query-string`.

https://github.com/sindresorhus/query-string/blob/master/index.d.ts

**Comment by sindresorhus** [comment]
Closing as this is most likely a Webpack problem.

**Comment by isaac1104** [comment]
@utazabanje Were you able to solve this? I'm having the same issue

**Comment by utazabanje** [comment]
@isaac1104 as I can remember I couldn't find a fix and opted out for a different solution

**Comment by isaac1104** [comment]
@utazabanje Oh okay! I was able to fix this by removing the node_modules folder and rebuilding my docker container. Thank you for your reply!
