### ISSUE TITLE
Add parameter skipEmptyString

### ISSUE THREAD

**Issue by vincent-aviva** [sindresorhus/query-string#244]
I love the skipNull that is available in the stringify.
Would it be posible to also include a skipEmpty parameter that filters all params where the value = ""

**Comment by sindresorhus** [comment]
Should be called `skipEmptyString`.

**Comment by mum-never-proud** [comment]
I have created a pr to add the support, kindly review and let me know if any changes are needed

https://github.com/sindresorhus/query-string/pull/252

thanks :)
