### ISSUE TITLE
Typing for `arrayFormatSeparator` is wrong in StringifyOptions

### ISSUE THREAD

**Issue by ksnyde** [sindresorhus/query-string#247]
On this line: https://github.com/sindresorhus/query-string/blob/master/index.d.ts#L64 the type is set to be `'string'` but it should be a `string`. This typing prevents setting any separator other than the literal string "string" which I think was an easy mistake to make but a mistake none-the-less :)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/commit/338072aab4a2c1c30060d7de7e8f397f3339cf99
