### ISSUE TITLE
Encode object as associative array

### ISSUE THREAD

**Issue by link365dev** [sindresorhus/query-string#250]
Source: `{order:{id: 'asc', date: 'desc'}}`

Expected Result: `order[id]=asc&order[date]=desc`

I tried: `JSON.stringify({order:{id: 'asc', date: 'desc'}}, {arrayFormat: 'index'})`
but it gave me: `{"order":{"id":"asc","date":"desc"}}`

If this already supported, what option should I provide?

**Comment by sindresorhus** [comment]
That's not supported and not something I want to support. It comes with way too many problems. I would recommend https://github.com/ljharb/qs instead if you need that.
