### ISSUE TITLE
Leading ? is not being removed

### ISSUE THREAD

**Issue by ryan-rushton** [sindresorhus/query-string#253]
When using query string to parse 
```
http://localhost:3000/redirect?code=2a4817a4b06d03059873
```

The leading string is not being removed.

The code I am using is the following,
```
const { location } = window;
console.log(location.search);
const parsed = parse(location.search);
console.log(parsed);
```

which results in 
```
?code=2a4817a4b06d03059873
{?code: "2a4817a4b06d03059873"}
```

I am using version 6.11.1.

**Comment by jfmoy** [comment]
You should check that you are importing `query-string` and not `querystring`.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/blob/bed0871911950cde14bbe2784c7cf3f16fab5c82/test/parse.js#L4-L6

**Comment by ryan-rushton** [comment]
Ah yes that is most likely the issue.  I didn’t realise querystring was even a thing. Thanks @jfmoy
