### ISSUE TITLE
Feature request: query-string strip (`pick`, `exclude`)

### ISSUE THREAD

**Issue by zhangciwu** [sindresorhus/query-string#259]
To eliminate unneeded params, preserve only needed
```js
queryString.strip('http://example.com/?a=1&b=2', [ 'a' ] )
// result : http://example.com/?a=1
```

It would be helpful when page has many redudant params (like statistic params) and want to get a cleaner one

---
Better function names from @Uzlopak:
```js
queryString.pick('http://example.com/?a=1&b=2', [ 'a' ] )
// result : http://example.com/?a=1


queryString.exclude('http://example.com/?a=1&b=2', [ 'a' ] )
// result : http://example.com/?b=2
```

**Comment by Uzlopak** [comment]
`strip` is not a very obvious naming. Do you keep the ones you name or do you drop the ones you name?

`pick` or `exclude` should better names for this type of operation.

**Comment by zhangciwu** [comment]
@Uzlopak `strip` is inspired by python string strip (remove spaces at two ends)
this word means 'remove all coverings from.'

And yes, it's not suit for exact function name for its inaccuracy，`pick` or `exclude` are better choices. (Maybe both can be implement)

**Comment by Uzlopak** [comment]
The python `strip` equivalent in javacscript would be `trim`

**Comment by sindresorhus** [comment]
I would name it `.removeElements()`

**Comment by zhangciwu** [comment]
For a better implementation, this could preserve the order of url queries, cause input and output are both strings, which has order.

**Comment by Uzlopak** [comment]
I would still prefer pick and exclude as removeElements could imply that you make not an idempotent operation.

**Comment by BenoitSerrano** [comment]
Just opened a PR here that provides what you want : [https://github.com/sindresorhus/query-string/pull/261](https://github.com/sindresorhus/query-string/pull/261) ;)

**Comment by zhangciwu** [comment]
@BenoitSerrano Good job! How about consider the order? https://github.com/sindresorhus/query-string/issues/259#issuecomment-629629534?

**Comment by Uzlopak** [comment]
@zhangciwu 
@BenoitSerrano 

I read the code, and I think it is reversing the order, by doing 

`return Object.assign({[currentKey]: query[currentKey]}, accumulator);`

To conserve the order I suppose you would actually have to do it the other way round. 

like
`return Object.assign(accumulator, {[currentKey]: query[currentKey]});`
or
`return Object.assign({}, accumulator, {[currentKey]: query[currentKey]});`

But i didnt test it...

**Comment by zhangciwu** [comment]
@Uzlopak In ES2020 Object do preserve **create** order, but early versions there is no limitation, so it may have different result for different browser/node/other runtime

> With this proposal, under most circumstances, for..in, Object.keys / values / entries, and JSON.stringify are guaranteed to iterate in order over:
> (1) Numeric array keys
> (2) non-Symbol keys, in insertion order
> (3) Symbol keys, in insertion order

Relate: https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties

**Comment by BenoitSerrano** [comment]
Updated it, it should preserve the parameters order ;)

**Comment by Uzlopak** [comment]
looks good for me

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt and feedback in https://github.com/sindresorhus/query-string/pull/261.
