### ISSUE TITLE
use as script file?

### ISSUE THREAD

**Issue by yairEO** [sindresorhus/query-string#262]
i don't have bundler, I don't have NPM, I need to use this script in a static HTML file, what it's unclear how, since I don't see anything of relevance on the `window` Object.

Is there some global which i'm missing? thanks.

**Comment by sindresorhus** [comment]
You can get it here: https://wzrd.in/standalone/query-string@6.12.1

Though note that it's only bundled and minified, not transpiled. So it will only work in modern browsers.

If you don't like bundling, I would recommend checking out https://www.snowpack.dev
