### ISSUE TITLE
Adjusting for..of loops for older Browsers

### ISSUE THREAD

**Issue by geoalexidis** [sindresorhus/query-string#266]
Hi guys,

I've seen that you have changed your `forEach` loops to `for..of` loops from version 5 to 6.

This breaks the usage in older browsers and even with my usage of the most up to date create-react-app this isn't getting transpiled properly.

Would you accept a pull request using `forEach` loops from me or what is actually the reason behind this change?

I'm using now version 5 but would like to keep up with the latest.

Thanks and best regards.

PS: There might be another reason why `for..of` aren't transpiled but I haven't dug too much in it.
See: https://daverupert.com/2017/10/for-of-loops-are-bad/

**Comment by sindresorhus** [comment]
> This module targets Node.js 6 or later and the latest version of Chrome, Firefox, and Safari. If you want support for older browsers, or, if your project is using create-react-app v1, use version 5: npm install query-string@5.

I have no intention of changing anything to make it compatible with older browser, sorry.
