### ISSUE TITLE
.parse() parseBooleans option not working

### ISSUE THREAD

**Issue by leonimurilo** [sindresorhus/query-string#267]
I tried using the option on the newest version of the package and the option does not work (I even tried the example)

**Comment by sindresorhus** [comment]
The tests disagrees: https://github.com/sindresorhus/query-string/blob/3b4c2959c0294a146eb48f7fa32f56d3e036008b/test/parse.js#L272-L275

**Comment by stasilo** [comment]
This seems to be the case for v5.1.1, though. Tried with example: 
```
queryString.parse('foo=true', { parseBooleans: true })
// => {foo: "true"}
```

**Comment by sedghi** [comment]
not working for me either
