### ISSUE TITLE
replacing '+' with spaces

### ISSUE THREAD

**Issue by Noob7** [sindresorhus/query-string#268]
Hey, 
 I have an email which has '+' in it. Its an auto-generated email we use for automation. But digging through your code i could find this line in the 'parse' method:
		let [key, value] = splitOnFirst(options.decode ? param.replace(/\+/g, ' ') : param, '=');
which is replacing '+' with spaces and Im not sure why. Can you provide some way around this?
This is my email:
collabctg+drtaogmbuqmsvkz+ecomm-test@gmail.com

**Comment by sindresorhus** [comment]
Duplicate of #119
