### ISSUE TITLE
Warning on Angular 10

### ISSUE THREAD

**Issue by menaheme** [sindresorhus/query-string#271]
i am using query string to build GET requests in an Angular app.

Recently, after updating to Angular 10,  i started getting build warnings,saying that using query string may hinder the package size, since its a commonjs dependecy.

Heres the warning from the angular blog
![warning](https://user-images.githubusercontent.com/5694495/87882659-3cfe3d80-ca0a-11ea-993b-f5aecd8a8e80.png)

And here`s the link to the article https://blog.angular.io/version-10-of-angular-now-available-78960babd41

**Comment by sindresorhus** [comment]
While it can be true in some cases (it's not in this case), adding a warning for all CommonJS packages is just total nonsense by the Angular team. Most packages on npm are CommonJS.
