### ISSUE TITLE
ParserQuery should not have "undefined" in the type

### ISSUE THREAD

**Issue by mortoray** [sindresorhus/query-string#273]
The ParserQuery type allows a key to have an "undefined" value. This appears to be an error, as there is no way for a query-string to specify an "undefined" value. It could be a "null", or an empty string, but undefined doesn't make sense.

```
export interface ParsedQuery<T = string> {
	[key: string]: T | T[] | null | undefined;
}
```

This is causing me trouble now as we're trying to interop with JSON types which cannot contain an undefined value.

**Comment by cdeutsch** [comment]
FWIW, I'm in the opposite boat (relying on `undefined` support), and 16.3.2 breaks my code.

Probably should have been a major version bump for this.

**Comment by mortoray** [comment]
I guess stringifyUrl  should still allow a type that allows `undefined`. Is that what is causing the trouble? The input type can be more lenient than the output type.

**Comment by cdeutsch** [comment]
> I guess stringifyUrl should still allow a type that allows undefined. Is that what is causing the trouble? 

Yeah. Building up an object to pass to it.
