### ISSUE TITLE
Support deeply nested arrays

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/query-string#274]
When using the Sendanywhere API, the following query parameters:

```js
{
	files: [{
		name: 'a.txt',
		size: 1
	}, {
		name: 'b.txt',
		size: 2
	}]
}
```

should be encoded like so:

```
file[0][name]=a.txt&file[0][size]=1&file[1][name]=b.txt&file[1][size]=2
```

This sort of format is currently the default when using `$.param()`.

It is almost achieved by `arrayFormat: 'index'` but it incorrectly serialized the objects as `[object Object]`.

## Helpful resources

- [$.param() implementation](https://github.com/jquery/jquery/blob/3d62d5704989f17d3a20ae7521d52e9c8c60b4ee/src/serialize.js#L55)
- [jquery-param reimplementation](https://github.com/knowledgecode/jquery-param/blob/cbf6334839566a75f99ab9f9895c76ab973f4eaf/src/index.js#L10) (also works)

// @sindresorhus

**Comment by sindresorhus** [comment]
I intentionally didn't want to open that can of worms (and potential security issues). For your needs, you'll have to use https://github.com/ljharb/qs

**Comment by sindresorhus** [comment]
Documented here: https://github.com/sindresorhus/query-string#nesting
