### ISSUE TITLE
IE8 doesn't support Object.keys()

### ISSUE THREAD

**Issue by jsmits21** [sindresorhus/query-string#28]
Consider putting a polyfill in the code:

    if (!Object.keys) {
      Object.keys = function(obj) {
        var keys = [];

        for (var i in obj) {
          if (obj.hasOwnProperty(i)) {
            keys.push(i);
          }
        }

        return keys;
      };
    }

I know, I know... Who the hell still supports IE8 right?

**Comment by sindresorhus** [comment]
Just put it in your own code. I'm not interested.

**Comment by jsmits21** [comment]
Lol I did.
