### ISSUE TITLE
arrayFormat: 'comma' option doesn't work

### ISSUE THREAD

**Issue by vineetdigit** [sindresorhus/query-string#285]
I'm using query-string@6.13.5

`queryString.stringify({foo: [1, 2, 3]}, {arrayFormat: 'comma'});` returns **foo=1&foo=2&foo=3** whereas the expected output is **foo=1,2,3**

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/blob/642772255027f721a952592b88f1b957d433c428/test/stringify.js#L120-L127

You're either using an old version of this package or a different query string package.
