### ISSUE TITLE
Support for undefined has been dropped

### ISSUE THREAD

**Issue by DeadEnglish** [sindresorhus/query-string#286]
When defining query params I have been defining them as follows:

```
export interface IQueryParams extends ParsedQuery {
	search?: string;
	pageNumber?: string;
}
```

Recently I've been seeing the following TS error `Property 'search' of type 'string | undefined' is not assignable to string index type 'string | string[] | null'.` Which looks like it's coming the following file: https://github.com/sindresorhus/query-string/blob/642772255027f721a952592b88f1b957d433c428/index.d.ts#L142

**Comment by sindresorhus** [comment]
You could probably have dug this up too from the release notes (https://github.com/sindresorhus/query-string/releases/tag/v6.13.2): https://github.com/sindresorhus/query-string/issues/273 This was an intentional change as the parsing would never return `undefined`.
