### ISSUE TITLE
arrayFormat is not working in chrome older versions

### ISSUE THREAD

**Issue by ajmalp5** [sindresorhus/query-string#292]
input : stringify({ extra_fields : ['users', 'tasks'] }, { arrayFormat: 'comma' })

output : extra_fields=users,tasks
(it works in chrome Version 86.0.4240.183 (Official Build) (x86_64))

it is not working in chrome version 84.
its getting like this output format
output : extra_fields=users&extra_fields=tasks

**Comment by sindresorhus** [comment]
Sounds like there was a bug in the older Chrome version that was later fixed. I have no interest of working around bugs in older Chrome versions though.
