### ISSUE TITLE
ParsedQuery interface is not compatible with ParsedQs interface from 'qs'

### ISSUE THREAD

**Issue by PavelKoroteev** [sindresorhus/query-string#297]
Hello, everyone!

Next code is not works out of the box.

```
import queryString, { ParsedQuery } from 'query-string';
import { ParsedQs } from 'qs';
```

TS2345: Argument of type 'ParsedQuery<string>' is not assignable to parameter of type 'ParsedQs'.  
Index signatures are incompatible. 
Type 'string | string[] | null | undefined' is not assignable to type 'string | ParsedQs | string[] | ParsedQs[] | undefined'.       Type 'null' is not assignable to type 'string | ParsedQs | string[] | ParsedQs[] | undefined'.

I understand that maybe we have causes for this, but I quess that fix is minor but very helpful.

Thank you, sorry for my English :)

**Comment by sindresorhus** [comment]
These are different packages with different ways of working. I'm not sure why you're expecting them to just be seamlessly convertible. It's up to you to resolve this type incompatibility.
