### ISSUE TITLE
v6.13.4 typing for `StringifiableRecord` breaks a couple of typescript things

### ISSUE THREAD

**Issue by mantagen** [sindresorhus/query-string#298]
The commit in question: https://github.com/sindresorhus/query-string/commit/38906bcec0fe7eb1bb0a9578c19c4ceffa9ffd10

I'm guessing you're aware of this as I've seen you've commented on https://github.com/Microsoft/TypeScript/issues/15300,  but as a result of this change, there are two problems that I've noticed which are that:
1. Only objects typed as a `type` are accepted, `interface`s give the error "Index signature is missing in type..."
```ts
interface Query {
  foo: string;
}

const query: Query = {
  foo: "bar"
};

querystring.stringify(query);
// Argument of type 'Query' is not assignable to parameter of type 'Record<string, string | number | boolean | readonly Stringifiable[] | null | undefined>'.
// Index signature is missing in type 'Query'.
```
2. Rest parameters can no longer be passed to `stringify`, for the same reason https://github.com/microsoft/TypeScript/issues/42021
```ts
const queryWithExtraBits = {
  foo: "bar",
  baz: "bang"
};

const { foo, ...query } = queryWithExtraBits;

querystring.stringify(query);
// Argument of type '{ baz: string; }' is not assignable to parameter of type 'Record<string, string | number | boolean | readonly Stringifiable[] | null | undefined>'.
// Index signature is missing in type '{ baz: string; }'.
```

Was this a conscious choice? Was it decided that typing for stringifiability was more important that being able to do either of the above?

**Comment by sindresorhus** [comment]
Not intentional. I had forgotten about that TS issue. Fixed: https://github.com/sindresorhus/query-string/releases/tag/v6.13.8

**Comment by mantagen** [comment]
Awesome, thanks :)

**Comment by sbaechler** [comment]
The type declaration still has a TODO 

````typescript
export function stringify(
	// TODO: Use the below instead when the following TS issues are fixed:
	// - https://github.com/microsoft/TypeScript/issues/15300
	// - https://github.com/microsoft/TypeScript/issues/42021
	// Context: https://github.com/sindresorhus/query-string/issues/298
	// object: StringifiableRecord,
	object: Record<string, any>,
	options?: StringifyOptions
): string;
````

https://github.com/sindresorhus/query-string/blob/main/base.d.ts#L425-L433
