### ISSUE TITLE
Arrays should not be sorted

### ISSUE THREAD

**Issue by ppershing** [sindresorhus/query-string#30]
Arrays should be serialized in the given order and not by sorting their values. This leads to unexpected surprises for APIs which are sensitive to ordering, e.g.

Example:
```
queryString.stringify({
    routing: 'car',
    route: ["London", "Berlin"],
});
```
should produce
`routing=car&route=London&route=Berlin` instead of the current result`routing=car&route=Berlin&route=London`

**Comment by sindresorhus** [comment]
Query strings are orderless, so are objects in JS btw.

**Comment by ppershing** [comment]
I know that arrays in query strings are not formally standarized and are server-specific (some use multiple ```var[]=...&var[]=...```, some just multiple ```var=...&var=...```), however arrays definitely have their order and the current implementation simply does not pass a sanity test ```assert equals(obj, parse(stringify(obj))```

**Comment by mrkam** [comment]
I'd like to reopen this issue. How can I do that?

It was closed with "Query strings are orderless, so are objects in JS btw." but the original question was not about keys in the JS objects, but values of the same key which are in an ordered array:
i. e. `route=Berlin&route=London` vs `route=London&route=Berlin`

For example, ElasticSearch uses order of sort parameters to specify order of sort and it is important to preserve the order. I completely support ppershing commit. See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html

> sort

> Sorting  to perform. Can either be in the form of fieldName, or fieldName:asc/fieldName:desc. The fieldName can either be an actual field within the document, or the special _score name to indicate sorting based on scores. There can be several sort parameters (order is important).
