### ISSUE TITLE
Bug: parse query `/#/?foo=a` 

### ISSUE THREAD

**Issue by zxh326** [sindresorhus/query-string#309]
parse `/#/?foo=a` 

result:
```js
{
    /?foo: a
}
```
Except:
```js
{
	foo: a
}
```

**Comment by sindresorhus** [comment]
That is not a supported format:

> Parse a query string into an object. Leading ? or # are ignored, so you can pass location.search or location.hash directly.

**Comment by zxh326** [comment]
> That is not a supported format:
> 
> > Parse a query string into an object. Leading ? or # are ignored, so you can pass location.search or location.hash directly.

ok, fine
