### ISSUE TITLE
Shouldn't parse the question mark

### ISSUE THREAD

**Issue by afshin-hoseini** [sindresorhus/query-string#311]
Also as documented, the question mark at the start of string shouldn't be considered as a part of first parameter's name.

This snippet:

```
queryString.parse('?code=123')
```
results `{'?code':'123'}`

Here is also a screen shot from the console:

![image](https://user-images.githubusercontent.com/15011928/114701146-a90e9780-9d37-11eb-9bff-abcc5c335cd1.png)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/blob/20992772758fc74188db64e789535469adaf241f/test/parse.js#L5

You're probably using `querystring` instead of `query-string`.

**Comment by afshin-hoseini** [comment]
@sindresorhus 
# 🤦🏻‍♂️
I am resigning today  🥲

**Comment by cmaster11** [comment]
> @sindresorhus
> 
> # 🤦🏻‍♂️ I am resigning today 🥲

I feel you

**Comment by BugKiller-tech** [comment]
I met the same issue today. I just imported 'querystring' instead of 'query-string'

**Comment by iKrushYou** [comment]
Ran into this issue today, thankfully I'm not the first :)

**Comment by debaraj-barua** [comment]
![I am SMRT](http://www.quickmeme.com/img/38/383ecc8afd8d21a502ed92ebfcfc060a615a644993bad9b127755f7c60d54582.jpg)

So I am not the only smrt one  

I basically copied the package from the very place I was instructed `not` to. 

![Screenshot 2021-08-30 at 13 27 22](https://user-images.githubusercontent.com/15277963/131332402-bc2ef6ba-ef01-4530-95e6-e303f804b758.png)

**Comment by ackmanx** [comment]
The frustrating part about this for me was that I actually installed `query-string` but apparently have `querystring` installed from another dependency so when Intellij auto-imported the latter I didn't notice 😮‍💨
