### ISSUE TITLE
skipNull and skipEmptyString are not working as intended

### ISSUE THREAD

**Issue by closingin** [sindresorhus/query-string#313]
Hello there!

I've just installed `query-string@^5.1.1` on my project, and both `skipNull` and `skipEmptyString` are not working as intended, they do not remove null/empty items from the returned string :thinking: 

I checked against a sample from your documentation:
```js
queryString.stringify({ a: 1, b: '', c: null, d: 4 }, {
    skipNull: true,
    skipEmptyString: true
})
// a=1&b=&c&d=4
```

Maybe a regression?

**Comment by sindresorhus** [comment]
You're not using the latest version of this package.

**Comment by closingin** [comment]
Oh my. I'm so sorry, my npm installed this version by default, I don't know why. Thanks.
