### ISSUE TITLE
This search string can not parse

### ISSUE THREAD

**Issue by wustzhaohui** [sindresorhus/query-string#315]
`/login?backUrl=/main/base/detail/advice?deepStatus=finished&sha1=42641560ee46c4b9be7776f3153a1294fba63720`

In this search, I only want to parse backUrl. Btt the result is 
```
{
   backUrl: '/main/base/detail/advice',
  deepStatus: 'finished'
}
```
I don't know if this is a bug.

**Comment by sindresorhus** [comment]
You must encode the URL in the `backUrl` query.

**Comment by wustzhaohui** [comment]
> You must encode the URL in the `backUrl` query.

I user the Escape and Unescape to translate the url.

**Comment by sindresorhus** [comment]
The URL you shared here does not have the second `?` escaped.

**Comment by wustzhaohui** [comment]
> The URL you shared here does not have the second `?` escaped.

I just escape the params of `backUrl` 's value.
