### ISSUE TITLE
Stringify Object Accordingly

### ISSUE THREAD

**Issue by alanyong91** [sindresorhus/query-string#319]
Just curios, is it possible to render the string accordingly? 

Example:
```    
import qs from 'query-string';

const queryObject = {
  sort: 'name',
  order: 'ASC',
  page: 100,
  limit: 1
}

const qsStringify = qs.stringify(queryObject)
console.log(qsStringify)
```

The Outcome:
`limit=1&order=ASC&page=100&sort=name`

Expected result:
`sort=name&order=ASC&page=100&limit=1`

**Comment by sindresorhus** [comment]
Please read the docs.
