### ISSUE TITLE
Is there a way to avoid ignoring the ending ampersand when parsing?

### ISSUE THREAD

**Issue by davidsu06** [sindresorhus/query-string#321]
Hi, actually if there is an ending ampersand in the string it's ignored, could be possible to avoid this behaviour? For example if I'm manually typing an url and I have to parse it every time I type, if I try to add more query-strings it won't be possible when I type the ampersand.

Thanks.

**Comment by sindresorhus** [comment]
This is not really a problem for this package to solve. You can force add it yourself after running this package.
