### ISSUE TITLE
Why am I getting this?

### ISSUE THREAD

**Issue by exzos28** [sindresorhus/query-string#324]
```
const link = "http://localhost:19006/farmAction?action=register&ref=utm_source&ver=1.0.2"
const parsed = queryString.parse(link);
```

Why are `http://localhost:19006/farmAction/?action` in the object?

![image](https://user-images.githubusercontent.com/39951413/129725336-8dc1bad9-8839-4750-93e3-13af19470264.png)

**Comment by sindresorhus** [comment]
You need to use the `.parseUrl` method.
