### ISSUE TITLE
can i fork epo and publish npm package?

### ISSUE THREAD

**Issue by sacru2red** [sindresorhus/query-string#329]
I want this app to transpile es5

I read same issues and your opinion like [this](https://github.com/sindresorhus/split-on-first/issues/3)

but, I'm don't understand MIT lisense
so I wonder Its possible, Can I fork repo and publish npm package?

thank you.

ps. sorry my english

**Comment by sindresorhus** [comment]
> but, I'm don't understand MIT lisense

This is not the place to ask about the MIT license. There are lots of resources about it if you google it.

> so I wonder Its possible, Can I fork repo and publish npm package?

Yes, as long as you preserve the license and credit.
