### ISSUE TITLE
Why replace + with space when parsing?

### ISSUE THREAD

**Issue by alyssaq** [sindresorhus/query-string#33]
Why replace '+' with space in [L20](https://github.com/sindresorhus/query-string/blob/master/index.js#L20)?

Breaks the parsing of this URL:
http://localhost:3000?startTime=2015-08-10T00:00:00+08:00&endTime=2015-08-20T04:00:00+08:00

    > querystring.parse(location.search)
    {
        endTime: "2015-08-20T04:00:00 08:00",
        startTime: "2015-08-10T00:00:00 08:00"
    }

No longer a valid ISO-8601 timestamp :(

**Comment by sindresorhus** [comment]
The `+` character has a semantic meaning in a query string and needs to be escaped.

Read more here: http://stackoverflow.com/a/6855723/64949

Looks like a bug in whatever you use to stringify the query string.

-

Node.js has the same behaviour:

```
$ node -e "console.log(require('querystring').parse('startTime=2015-08-10T00:00:00+08:00&endTime=2015-08-20T04:00:00+08:00'))"
{ startTime: '2015-08-10T00:00:00 08:00',
  endTime: '2015-08-20T04:00:00 08:00' }
```

**Comment by kevinsearle** [comment]
Would like to point out that [RFC 3986 Uniform Resource Identifier (URI): Generic Syntax](https://tools.ietf.org/html/rfc3986#section-2.2) lists "+" as a reserved character but doesn't mention it as being a space. This is just assumed behavior by the community at-large from what I understand.

**Comment by sindresorhus** [comment]
@kevinsearle I'm just adhering to reality here. Even the new WHATWG `URL` standard does this:

```js
console.log((new URL('https://example.com/?abc=foo+bar')).searchParams.get('abc'));
//=> 'foo bar'
```

**Comment by kevinsearle** [comment]
Makes sense to me.
