### ISSUE TITLE
Parse function returns wrong value with options of separator and "&" symbol

### ISSUE THREAD

**Issue by elwiiman** [sindresorhus/query-string#330]
Hello! My Issu is the following. 

The documentation says:
```
queryString.parse('foo=1|2|3', {arrayFormat: 'separator', arrayFormatSeparator: '|'})
 //=> {foo: ['1', '2', '3']}
```
So, if I use a separator equal to an "&" the return value is:
```
queryString.parse('foo=1&2&3', {arrayFormat: 'separator',arrayFormatSeparator: '&'})
//=>{2: null, 3: null, foo: '1'}
```
If I use the same separator options in stringify function, it works ok. 

This happens with the last version of query-string: "7.0.1"

**Comment by sindresorhus** [comment]
The `&` needs to be escaped since it's used in a query item value and not as a query item separator.

This behavior is the same with the native browser APIs:

```js
let x = new URLSearchParams('foo=1&2&3');

x.get('foo');
//=> "1"
```
