### ISSUE TITLE
Document breaking changes from 6.x.x to 7.x.x

### ISSUE THREAD

**Issue by matthewmayer** [sindresorhus/query-string#331]
What are the breaking changes from 6.x.x to 7.x.x? Could this be documented in a CHANGELOG to make it easier for consumers to upgrade without fear of breaking something?

**Comment by matthewmayer** [comment]
OK after some searching I found this - https://github.com/sindresorhus/query-string/pull/304 - i think this should be linked to from the README.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/releases (This should honestly be the first place to look)

**Comment by matthewmayer** [comment]
Sorry for some reason this didn't show up for me on mobile!

**Comment by tony** [comment]
I was trying to see the changes across recent releases just now.

I find really hard to comprehend GitHub releases due to the layout, pagination, spacing, etc. 

Everyone's different - every digression from a single file, curated changelog makes it more frustrating to understand and track changes.
