### ISSUE TITLE
when encode  char `+` , will get a space

### ISSUE THREAD

**Issue by JackySoft** [sindresorhus/query-string#332]
Question：

Chinese：开发登录时，后台返回一个token，其中包含特俗字符，比如：加号，但是通过query-string进行转换以后，发现变成了空格。

English：During development login, the background returns a token containing special characters, such as a plus sign. However, after conversion through query string, it is found that it becomes a space.

My Code:
```js
import QueryString from 'query-string';

let token = 'token=Hbs+QbOotpyFj';
let params = QueryString.parse(token);
console.log(params)

print:
token=Hbs QbOotpyFj
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string#why-is-it-parsing--as-a-space
