### ISSUE TITLE
Is possible to use slash instead question mark and equal sing?

### ISSUE THREAD

**Issue by bilalmalkoc** [sindresorhus/query-string#342]
```
queryString.stringifyUrl({ 'site.com', query: { foo: ['param-1, 'param-2'] } }, { arrayFormat: 'separator', arrayFormatSeparator: '+' });
// => site.com?foo=param-1+param-2
```

Can i make result like this?
`// => site.com/foo/param-1+param-2`

**Comment by sindresorhus** [comment]
No. A slash indicates it's still the path. Your question is not specific to this library. This is just how query strings work generally.

https://en.wikipedia.org/wiki/Query_string
