### ISSUE TITLE
unable to parse url having multiple question mark (?)

### ISSUE THREAD

**Issue by Harshmakadia** [sindresorhus/query-string#343]
I have a URL, and if the user is not logged in, I store that URL in query param.

Here is how the URL looks like 
http://localhost:3000/?redirectTo=https://devs-homed.mart.xyz/new-project?type=badminton&code=pitchford&sessionExpired=true

```
const url = http://localhost:3000/?redirectTo=https://devs-homed.mart.xyz/new-project?type=badminton&code=pitchford&sessionExpired=true

const { redirectTo } = query.parse(url);

console.log(redirectTo)
Output => https://devs-homed.mart.xyz/new-project?type=badminton

Expected => https://devs-homed.mart.xyz/new-project?type=badminton&code=pitchford&sessionExpired=true
```

How can I get the expected output? 

I know this issue is because there is multiple question mark (?) in the URL any way I can solve this issue?

**Comment by sindresorhus** [comment]
You have to encode `https://devs-homed.mart.xyz/new-project?type=badminton&code=pitchford&sessionExpired=true` using `encodeURIComponent`.
