### ISSUE TITLE
why query-string encode the fragmentIdentifier?

### ISSUE THREAD

**Issue by luckymore** [sindresorhus/query-string#346]
```js
queryString.stringifyUrl({
	url: 'https://foo.bar',
	query: {
		top: 'foo'
	},
	fragmentIdentifier: '/bar/hello'
});
// => 'https://foo.bar?top=foo#%2Fbar%2Fhello'
```

if set `{ encode: false }`, the other query also won't be encoded

**Comment by sindresorhus** [comment]
That looks like a bug. Here's how the native `URL` behaves:

```js
let x = new URL('https://foo.bar');
x.hash = '/bar/hello';

x.toString();
//=> 'https://foo.bar/#/bar/hello'
```

**Comment by sindresorhus** [comment]
// @Mark1626

**Comment by hanbin9775** [comment]
Created PR first, forgive me if messed up with the contribution flow.
I'm kind of newbie in this opensource environment.

I found that fragmentIdentifier were encoded with encodeURIComponent method.
It should be encoded with encodeURI method.
