### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by jaweii** [sindresorhus/query-string#348]
I created a project with create-react-app, when I build the project and visit it in browser, it throw the error:

```
Uncaught ReferenceError: exports is not defined
    at 668 (index.js:288:1)
    at n (bootstrap:19:32)
    at 3953 (types.ts:160:13)
    at n (bootstrap:19:32)
    at startup:4:27
    at startup:4:47
```

<img width="660" alt="image" src="https://user-images.githubusercontent.com/22613580/197473617-69af0cb7-f493-41d9-bb0f-d12975297b49.png">

**Comment by sindresorhus** [comment]
This is not the place to ask for CRA support. You may want to try the latest release though: https://github.com/sindresorhus/query-string/releases/tag/v8.0.0
