### ISSUE TITLE
dependency decode-uri-component is vulnerable to Denial of Service

### ISSUE THREAD

**Issue by chrstph-dvx** [sindresorhus/query-string#349]
`decode-uri-component` 0.2.0 version is vulnerable to Denial of Service

Github advisory:
https://github.com/advisories/GHSA-w573-4hg7-7wgq

Relevant issue in `decode-uri-component`:
https://github.com/SamVerschueren/decode-uri-component/issues/6

**Comment by chrstph-dvx** [comment]
Duplicate of #345, my bad

**Comment by benomatis** [comment]
@chrstph-dvx #345 is not the same, it's referring to https://github.com/SamVerschueren/decode-uri-component/issues/5, while, as you correctly referred to in your description, this vulnerability is actually reported in https://github.com/SamVerschueren/decode-uri-component/issues/6
