### ISSUE TITLE
Firefox – stops parsing on equal sign

### ISSUE THREAD

**Issue by steveluscher** [sindresorhus/query-string#35]
In Firefox, given the hash in the URL is `#code=var%20foo%20%3D%20'bar'%3B`:

```js
var queryString = require('query-string');
queryString.parse(location.hash);
```

Output:

```js
{code: 'var foo '}
```

Seems to stop parsing when it encounters an equal sign. Chrome works fine.

**Comment by SamVerschueren** [comment]
What version of firefox are you using? I tested it with Chrome and Firefox and both give me the correct result. My Firefox version is `41.0.1`.

**Comment by steveluscher** [comment]
# Firefox <=39

```
location.hash = "#code=var%20foo%20%3D%20'bar'%3B";
"#code=var%20foo%20%3D%20'bar'%3B"
location.hash
"#code=var foo = 'bar';"
```

# Firefox >=41.0.1

```
location.hash = "#code=var%20foo%20%3D%20'bar'%3B";
"#code=var%20foo%20%3D%20'bar'%3B"
location.hash
"#code=var%20foo%20%3D%20%27bar%27%3B"
```

You could mitigate this by changing your `split` strategy.

http://jsbin.com/gocoralatu/1/edit?js,console

**Comment by SamVerschueren** [comment]
Will have a look at it later this day.
