### ISSUE TITLE
Property 'parse' does not exist on type 'typeof import("/xxx/frontend/node_modules/query-string/index")'

### ISSUE THREAD

**Issue by esetnik** [sindresorhus/query-string#358]
Using the following code snippet I am getting a type error in v8.0.0

```ts
import queryString from 'query-string';

queryString.parse(window.location.search);
```

**Comment by sindresorhus** [comment]
Make sure you have [`"module": "node16", "moduleResolution": "node16"`](https://www.typescriptlang.org/tsconfig#module) in your tsconfig.json. *([Example](https://github.com/sindresorhus/tsconfig/blob/main/tsconfig.json))*

**Comment by sindresorhus** [comment]
Incorrect `target`.

**Comment by esetnik** [comment]
I also tried target `es2020` as per your example and faced the same issue.

**Comment by sindresorhus** [comment]
I works fine for me with this tsconfig.

**Comment by manojs2022** [comment]
@sindresorhus Same issue for me too. Tried your tsconfig.json and its still the same

**Comment by klassm** [comment]
Also does not work for me, also not with your tsconfig. Seems to be a general issue with version 8?

`error TS2339: Property 'stringify' does not exist on type 'typeof import("/workspace/query-string-8.x/node_modules/query-string/index")'.`

**Comment by raulfdm** [comment]
Having the same issue in my Remix project with `"module": "node16", "moduleResolution": "node16"]`

```
Property 'stringify' does not exist on type 'typeof import("/Users/raulmelo/development/raulmelo-studio/node_modules/.pnpm/query-string@8.0.0/node_modules/query-string/index", { assert: { "resolution-mode": "import" } })'.ts(2339)
```

<details>
<summary>tsconfig.json</summary>
```json
{
  "include": [
    "remix.env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "compilerOptions": {
    "lib": [
      "DOM",
      "DOM.Iterable",
      "ES2019"
    ],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "Node16",
    "module": "Node16",
    "resolveJsonModule": true,
    "target": "ES2019",
    "strict": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "paths": {
      "$infrastructure/*": [
        "./app/infrastructure/*"
      ],
      "$ui/*": [
        "./app/ui/*"
      ],
      "$screens/*": [
        "./app/screens/*"
      ],
    },
    // Remix takes care of building everything in `remix build`.
    "noEmit": true
  }
}
```
</details>

Even if I change the target to `ESNext` it doesn't work.

I noticed that the query-string `.d.ts` is being generated like this:

```ts
export * as default from './base.js';

export {
	type ParseOptions,
	type ParsedQuery,
	type ParsedUrl,
	type StringifyOptions,
	type Stringifiable,
	type StringifiableRecord,
	type UrlObject,
} from './base.js';
```

But if I change to this:

```diff
-export * as default from './base.js';
+import * as base from './base.js';

+export default base

export {
	type ParseOptions,
	type ParsedQuery,
	type ParsedUrl,
	type StringifyOptions,
	type Stringifiable,
	type StringifiableRecord,
	type UrlObject,
} from './base.js';
```

Than it works just fine. 🤔

**Comment by raulfdm** [comment]
Update: it seems if I change my `package.json` to `"type": "module"` the type problem goes away, however the entire project breaks because it cannot be ESM. :/

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/releases/tag/v8.0.1

**Comment by baraeb92** [comment]
I think this will not work because node16, as the target and module, is not yet supported by those using NextJS? @sindresorhus 

https://github.com/vercel/next.js/pull/44177

**Comment by rafakwolf** [comment]
It's not working with NestJS yet, I tried changing my tsconfig like so:
![image](https://github.com/sindresorhus/query-string/assets/2060578/45ee83cf-76b5-4f8b-9a26-9a182d2be57c)
@sindresorhus 
Thank you for any help
