### ISSUE TITLE
Any reason for dropping `null` from the types for `ParsedQueryString`

### ISSUE THREAD

**Issue by birtles** [sindresorhus/query-string#362]
Prior to c2ab7cd102fbc96d374c6a55deea20f1bf2929c4 ("Require Node.js 14 and move to ESM"), `ParsedQueryString` was [defined as](https://github.com/sindresorhus/query-string/commit/c2ab7cd102fbc96d374c6a55deea20f1bf2929c4#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L174-L176):

```ts
export interface ParsedQuery<T = string> {
	[key: string]: T | null | Array<T | null>;
}
```

But that patch [made it](https://github.com/sindresorhus/query-string/commit/c2ab7cd102fbc96d374c6a55deea20f1bf2929c4#diff-00c64f8e8b784a05b61fe9f6beea5fa6eedc3fd9e004d2aa24ff103fc547431cR174)

```ts
export type ParsedQuery<T = string> = Record<string, T | undefined | Array<T | undefined>>;
```

Was that change intentional? I can't see anything about it in the release notes and the docs still say that:

> Note that keys with `undefined` as the value are always skipped.

And if that's true, are we expecting to be passed back keys with `undefined` values from parsing while passing in `null` values for keys with don't have a value?

**Comment by sindresorhus** [comment]
It's a typo: https://github.com/sindresorhus/query-string/releases/tag/v8.0.3
