### ISSUE TITLE
Can no longer import specific exports in TypeScript

### ISSUE THREAD

**Issue by veloek** [sindresorhus/query-string#364]
Not sure if this was intentional, but it's no longer (with v8) possible to import specific exports in TypeScript, ex:
```
import { parse, stringify } from "query-string"
```

**Comment by MagicFame** [comment]
Yes, you can import with the following line 
`import queryString from 'query-string';`

and use after 
`queryString.stringify()`

**Comment by sindresorhus** [comment]
Duplicate of #363
