### ISSUE TITLE
Optional chaining operator (?.) is not supported in IE and other old browsers

### ISSUE THREAD

**Issue by lvxiaodi1234** [sindresorhus/query-string#368]
In error log monitor，I found some errors like "Uncaught SyntaxError: Unexpected token ." from old browsers（IE and so on）.
![image](https://github.com/sindresorhus/query-string/assets/26077502/2b8fe84a-40dd-4097-b703-5ed055d32ce4)

Debug file "base.js", the problem is optional chaining operator (?.) can not use directly in old browsers
<img width="949" alt="image" src="https://github.com/sindresorhus/query-string/assets/26077502/14d2cba9-a128-4c0e-99f2-444eeb18b8c8">

**Comment by sindresorhus** [comment]
From the top of the readme:

> For browser usage, this package targets the latest version of Chrome, Firefox, and Safari.

**Comment by thomasjm** [comment]
Using this operator seems to confuse terser for versions < 5.2.0: https://github.com/terser/terser/issues/567

Some parts of the ecosystem still use an older terser, so I think it would be better not to use the optional chaining operator in libraries.
