### ISSUE TITLE
Stringify Array of Object URL

### ISSUE THREAD

**Issue by mazipan** [sindresorhus/query-string#370]
Supporting Stringify for Array of Object.

Sample Parameter:

```ts
const params = {
  filters: [{
    key1: 'Value1'
  }, {
    key2: 'Value2'
  }]
}
```

Using:

```ts
qs.stringify(params, { 
   skipNull: true, 
   arrayFormat: 'bracket' 
})
```

Sample expected result: `/?filter[key1]=Value1&filter[key2]=Value2`

See in CodeSandbox: https://codesandbox.io/s/little-dew-q6jjvk?file=/src/index.js

**Comment by sindresorhus** [comment]
I don't plan to support objects in this package. There are other projects like `qs` that does.

https://github.com/sindresorhus/query-string#nesting
