### ISSUE TITLE
require() of ES Module

### ISSUE THREAD

**Issue by blackslayR** [sindresorhus/query-string#372]
require() of ES Module C:\path\node_modules\query-string\index.js from C:\path\client\node_modules\vue-server-renderer\build.dev.js not supported. Instead change the require of index.js in C:\path\client\node_modules\vue-server-renderer\build.dev.js to a dynamic import() which is available in all CommonJS modules.

this is my own package.json file

```{
  "name": "client",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.13.6",
    "flowbite": "^1.8.1",
    "nuxt": "^2.0.0",
    "query-string": "^8.1.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.15",
    "babel-eslint": "^10.0.1",
    "eslint": "^4.19.1",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^4.0.0",
    "postcss": "^8.4.28",
    "tailwindcss": "^3.3.3"
  }
}
```

This is my code

```
import queryString from 'query-string'

/// Rest of the code

export const actions = {
    async getCart ({ commit, state }) {
        let query = {}

        if (state.shipping) {
          query.shipping_method_id = state.shipping.id
        }
    
        let response = await this.$axios.$get(`cart?${queryString.stringify(query)}`)


// Rest of the code
```

i have tried adding "type": "module" to my own package.json file, and even downgraded to other version ended up with even more errors.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sindresorhus** [comment]
You probably need to enable ESM in your Vue/Nuxt server. This package uses correct ESM config, so the problem is with your build tool or config.

**Comment by bertyhell** [comment]
You can also downgrade to v7.x.x which is not an ESM build yet

**Comment by Dakuan** [comment]
@bertyhell thanks! all these ESM packages are ruining ts + node projects
