### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by adithp** [sindresorhus/query-string#375]
./node_modules/query-string/base.js 341:14
Module parse failed: Unexpected token (341:14)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
|   return {
>     url: url_?.split('?')?.[0] ?? '',
|     query: parse(extract(url), options),
|     ...(options && options.parseFragmentIdentifier && hash ? {

**Comment by adithp** [comment]
![Login js - travel-app - Visual Studio Code  Administrator  02-12-2023 15_54_05](https://github.com/sindresorhus/query-string/assets/61468791/c4429039-ee01-47dc-945e-4f4d5fffefd6)

**Comment by sindresorhus** [comment]
This is a problem with your Babel config, not this package.

**Comment by oskar-anderson** [comment]
@adithp Use version 7.1.3 if you don't want to adjust your config.

**Comment by chitwan001** [comment]
Hi @adithp , Did you find the solution or any workaround for this?
