### ISSUE TITLE
SyntaxError with importing queryString module

### ISSUE THREAD

**Issue by stacy-22** [sindresorhus/query-string#378]
Hello! After updating the package from version 7.1.3 to 8.2.0, I started experiencing syntax errors in my app. The import signatures and `queryString` methods usage are all according to your documentation. Hope for some help, thank you!

<img src="https://screenshot.click/06-47-jn362-xo2l0.png">

**Comment by sindresorhus** [comment]
This is a problem with your Jest config, not this package.

**Comment by dushmanta05** [comment]
I hope you've resolved issue, if someone else trying to resolve it you can add this below to your `package.json` file

```js
{
 "type": "module"
}
```
