### ISSUE TITLE
`key=null` parsing to `null`, not the string "null"

### ISSUE THREAD

**Issue by bombillazo** [sindresorhus/query-string#381]
Hey, Any reason why `queryString.parseUrl()` parses a query param with the value null as `null` and not the string "null"? Heres an output we get when using the function:
<img width="403" alt="image" src="https://github.com/sindresorhus/query-string/assets/44002321/e08bc14b-798d-4b32-b362-0326267a8ab4">

We expect values to parse to null only when they have the `key` (no =) format, not if the string value is also "null"

**Comment by sindresorhus** [comment]
Already works like that according to tests: https://github.com/sindresorhus/query-string/commit/3d8fbf2328220c06e45f166cdf58e70617c7ee68
