### ISSUE TITLE
Support passing a function or predefined config to `parseNumbers`

### ISSUE THREAD

**Issue by joeyfigaro** [sindresorhus/query-string#387]
I'm basically looking to achieve the opposite of #199 – I want `["123", "00A", "441"]` to remain `["123", "00A", "441"]`. For our current needs the only properties that would have these arrays are known ahead of time, and arrays don't appear anywhere else...so something like `{ parseNumbers: "except-arrays" }` would work. 

Alternatively, `parseNumbers` could take a function that receives the current value's associated key so we can provide a callback that returns true or false given the name of the property.  

If this is something you'd be interested in supporting, I'm happy to take a crack at a PR. 

Update: it looks like we could update [this area](https://github.com/sindresorhus/query-string/blob/3d8fbf2328220c06e45f166cdf58e70617c7ee68/base.js#L370-L378) if we ended up supporting callback functions for parseNumbers

**Comment by scottenock** [comment]
Hey @joeyfigaro , this behaviour is now possible via the types feature we implemented here: #385 

For your specific use case you would use the type `string[]`
```
test('Using types option: you can ignore parseNumbers for specific arrays', t => {
	t.deepEqual(queryString.parse('id=123&numberArray=123,00A,441&number=23', {
		arrayFormat: 'comma',
		parseNumbers: true,
		types: {
			id: 'number',
			numberArray: 'string[]'
		},
	}), {
		id: 123,
		numberArray: ['123', '00A', '441'],
		number: 23
	});
});
```

Let me know if I've missed something. Could you please close out this issue, cheers!
