### ISSUE TITLE
stringify method doesn't return a `?`

### ISSUE THREAD

**Issue by Javascipt** [sindresorhus/query-string#39]
This is the `stringify` example on the documentation : 

```javascript
location.search = queryString.stringify(parsed);

console.log(location.search);
//=> '?foo=unicorn&ilike=pizza'
```

You can notice the `?` at the begining, but in reality, [it doesn't return it](https://github.com/sindresorhus/query-string/blob/master/index.js#L45). I wanted to make a pull request, but I wasn't sure of what should be changed , the documentation or the code !

**Comment by sindresorhus** [comment]
`location.search` does return it, though:

```js
location.search = 'foo';
console.log(location.search);
//=> '?foo'
```

**Comment by Javascipt** [comment]
You're right, without the object `location` it doesn't ! I was using it on node not the browser. 
Thank's anyway. keep it up!
