### ISSUE TITLE
Provide typescript definitions

### ISSUE THREAD

**Issue by Strate** [sindresorhus/query-string#40]
Please provide typescript definitions

**Comment by SamVerschueren** [comment]
Why not write them yourselves? It's not that they are hard to write, especially not for a small module like this.

```js
declare module "query-string" {
	export function parse(str: string);
	export function stringify(obj: Object);
	export function extract(str: string);
}
```

**Comment by sindresorhus** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by SamVerschueren** [comment]
Will do a PR to put this one on DefinitelyTyped, it's not there yet (at least, can't find it).

**Comment by Strate** [comment]
Much better to provide typedefinitions by package itself, typescript has ability to autoload them from your `package.json` file: https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

**Comment by sindresorhus** [comment]
I'm not interested in maintaining that when I don't even use TypeScript.

**Comment by SamVerschueren** [comment]
You will have to do it with this one: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6955

@sindresorhus Guess you should give it a :+1: as they are asking every author to review the PR ([example](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6952)]

**Comment by Strate** [comment]
> I'm not interested in maintaining that when I don't even use TypeScript.

Users of your library use typescript. Will you accept PR?

**Comment by SamVerschueren** [comment]
Why? To make it easier for TypeScript devs? What if tomorrow another one is popping up, do we have to support that as well? A module has to be as small as possible imo. If someone wants to build things around it, fine (-> definitely typed). So I don't think a PR will get merged.
