### ISSUE TITLE
Is strict-uri-encode really necessary?

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/query-string#42]
I am using https://github.com/Sage/jsurl to efficiently encode JSON objects in the search string, and it uses the looser URI encoding range used by browsers, including the `'` character.

I also use rackt/history which uses query-string, which converts `'` to `%27`, which grows my urls, which makes me sad. Is there a reason the strict URI range should be used?

**Comment by sindresorhus** [comment]
It was introduced in https://github.com/sindresorhus/query-string/pull/29.

// @go-oleg @kevva

**Comment by wmertens** [comment]
Aww :-(

How about putting strict mode behind a flag?

On Thu, Dec 10, 2015, 6:19 PM Sindre Sorhus <notifications@github.com>
wrote:

> It was introduced in #29
> <https://github.com/sindresorhus/query-string/pull/29>.
>
> // @go-oleg <https://github.com/go-oleg> @kevva <https://github.com/kevva>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/query-string/issues/42#issuecomment-163692816>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by SamVerschueren** [comment]
Maybe it's browser support related? Not sure though, just guessing here.

**Comment by wmertens** [comment]
@SamVerschueren the reason for #29 afaict was that markdown parsers were parsing urls with strict interpretation of the relevant RFCs which caused URLs to not be completely linkified.

IMHO the markdown parser should be fixed, because markdown is a loose format that needs to be generous regarding its inputs. After all, anybody can copy a URL from a browser and it will have the looser URI character range.

So I would be really happy if query-string could revert its ways and make the behavior in #29 optional…

**Comment by sindresorhus** [comment]
I'm willing to put it behind an option if anyone does a good pull request with tests and docs, but it should be strict by default.

**Comment by wmertens** [comment]
<3 thanks @SamVerschueren! Now to get rackt/history to do the same :)
