### ISSUE TITLE
Expressing query params as arrays with a single element

### ISSUE THREAD

**Issue by kevana** [sindresorhus/query-string#44]
Hi, before [history](https://github.com/rackt/history) switched from qs I used array-value params:
```
{ // query object
  paramName: ['firstValue']
}
```
Which was serialized to:
```
?paramName[]=firstValue
```
So when it was re-parsed we'd end up with the same query object. It doesn't look like the query-string stringifier has a way to express array values with a single element, as a result the re-parsed query object is different than the original query object:
```
{
  paramName: 'firstValue'
}
```

Is there any way to achieve transitive stringify/parse behavior with this lib or is that out of scope? I can write my own custom parser/stringifier if needed.

**Comment by sindresorhus** [comment]
Out of scope. There are no specced or consistent way of doing nested query params. Different backends handle it differently.

See: https://github.com/sindresorhus/query-string#nesting
