### ISSUE TITLE
Don't mutate query params that are arrays when sorting their values before uri encoding

### ISSUE THREAD

**Issue by mattpetrie** [sindresorhus/query-string#46]
In `stringify(obj)`, properties on the query params object that are of type Array are [currently being sorted](https://github.com/sindresorhus/query-string/blob/master/index.js#L57) with `Array.prototype.sort()`, which mutates the original array. This causes errors for applications that use immutable data if the query params object being sent to `stringify` is frozen (or even if the object is not actually frozen, it can cause an undesired mutation of state). It may cause problems for other applications as well, if they are using the same object elsewhere and are not expecting the array order to be mutated.

This could be solved by just creating a new array in the sort rather than performing the sort on the original array. Happy to submit a pull request with a proposed fix if that would be helpful.

**Comment by sindresorhus** [comment]
Ugh. I always forget that `.sort()` mutates the array.
