### ISSUE TITLE
`require('query-string').parse('hasOwnProperty&hasOwnProperty');` breaks

### ISSUE THREAD

**Issue by cspotcode** [sindresorhus/query-string#47]
Unsafe usage of `hasOwnProperty` means that parsing certain query strings will throw an error.

The following cases are also not working correctly:

    qs.parse('__proto__');
    qs.parse('__proto__&__proto__');

`Object.create(null)` should fix the problem.

**Comment by sindresorhus** [comment]
Wanna do a pull request?

**Comment by cspotcode** [comment]
Sorry, I can't.  I'm busy with some other things at least for the time being.

**Comment by cspotcode** [comment]
Just a reminder that, as of v3.0.3, this bug is unresolved.

```
// Reproduction:
require('query-string').parse('hasOwnProperty&b');
```

**Comment by gabrielecirulli** [comment]
Just a side note, this should have been noted in some sort of a changelog (I couldn't find any, sorry if there is one and I didn't see it). I got bit by a case where I was using "hasOwnProperty" on a parsed query string and it stopped working.

**Comment by cspotcode** [comment]
@gabrielecirulli It's mentioned in the docs here: https://github.com/sindresorhus/query-string#parsestring

**Comment by gabrielecirulli** [comment]
Thanks for pointing me to it, I guess the lack of a changelog made that hard to glean.

**Comment by adamellsworth** [comment]
Oh gosh, everyone. This is easily the worst decision you could have made. If your code has to redefine the language your code was written in in order for your code to work, your code shouldn't be published. Still a problem in v4.3.1.
