### ISSUE TITLE
in arrays passed to stringify, `null` the same as string `"null"`

### ISSUE THREAD

**Issue by cspotcode** [sindresorhus/query-string#49]
I'm not sure if this is a bug; maybe it's intended or unspecified behavior.  Within an array, `null` is the same as the string `"null"`.

    var params = {'a': null, 'b': [null, 123]};
    require('querystring').stringify(params);
    // Node core: "a=&b=&b=123"
    require('query-string').stringify(params);
    // query-string: "a&b=123&b=null"

Here's my rationale:

    var qs = require('query-string');
    // If these are equivalent:
    qs.stringify({a: 123}) === qs.stringify({a: [123]});
    // These should be as well?
    qs.stringify({a: null}) === qs.stringify({a: [null]});

**Comment by sindresorhus** [comment]
Agreed. PR welcome :)
