### ISSUE TITLE
result from `parse` no longer has `hasOwnProperty` method

### ISSUE THREAD

**Issue by SpainTrain** [sindresorhus/query-string#50]
in 3.0.1, `parse` had the following behavior:

```
> qs.parse('my-param=my-val')
{ 'my-param': 'my-val' }
> qs.parse('my-param=my-val').hasOwnProperty
[Function: hasOwnProperty]
> qs.parse('h=j').hasOwnProperty
[Function: hasOwnProperty]
> qs.parse('').hasOwnProperty
[Function: hasOwnProperty]
```

in 3.0.2, the object returned no longer has the `hasOwnProperty` method:

```
> qs.parse('hbud-fixture=not-logged-in')
{ 'hbud-fixture': 'not-logged-in' }
> qs.parse('hbud-fixture=not-logged-in').hasOwnProperty
undefined
> qs.parse('hbudfixture=not-logged-in').hasOwnProperty
undefined
> qs.parse('hbudfixture=notloggedin').hasOwnProperty
undefined
> qs.parse('').hasOwnProperty
[Function: hasOwnProperty]
> qs.parse('h=j').hasOwnProperty
undefined
```

I am unsure whether this was considered part of the API, but some consumers rely on the behavior - https://github.com/mjackson/history/blob/master/modules/useQueries.js#L13

**Comment by SamVerschueren** [comment]
This is because of https://github.com/sindresorhus/query-string/issues/47

`hasOwnProperty` could be a query string property which interfered with the `hasOwnProperty` method of the object. Maybe the change should've been released as breaking @sindresorhus ?

**Comment by taion** [comment]
:+1: on this – #47 is a good change, but it'd be best to roll it back and release a v3.0.3 to avoid breaking people who are using the `for ... in`/`hasOwnProperty` pattern, then re-release as v4.0.0 so we can update our code.

**Comment by taion** [comment]
Actually, on second thought, this is somewhat problematic – it means that we need to not use `obj.hasOwnProperty` on anything coming out of `parseQuery` here, which is quite a lot to keep track of.

**Comment by cspotcode** [comment]
@taion: The `for ... in` / `hasOwnProperty` pattern should usually be done like this:

```
for(var key in obj) {
    if(Object.prototype.hasOwnProperty.call(obj, key) {
        // ...
    }
```

However, to avoid using `Object.create(null)` in `3.x.x` you could use `Object.defineProperty()` when attaching properties to the returned object.  That would avoid issues with `__proto__`.

Or, to keep things modular, you could use a microlibrary that implements safe get(), set(), and has() functions for using objects as dictionaries.

**Comment by taion** [comment]
You're right, but a lot of people write it as `obj.hasOwnProperty` instead of going up to `Object.prototype.hasOwnProperty`. It's a pretty big usability caveat.

Either way, though, this change in practice triggers enough bugs in consumers of this code that it should be released as breaking.

**Comment by Aweary** [comment]
Instead of `Object.create(null)` could you just do `Object.create({})

**Comment by cspotcode** [comment]
No, because the prototype of `{}` is still `=== Object.prototype`.  You'd
just be inserting another object into the prototype chain, when what you
want is to remove `Object.prototype` from the chain.

**Comment by Aweary** [comment]
Sorry, I removed my comment because I accidentally submitted it before I was done.

What I meant to write was something like:

```js

**Comment by cspotcode** [comment]
No, that wasn't what I was recommending.  What if someone relied on the `toString` method of an object?  You'd have to define that as well.  What if someone tried to parse `"hasOwnProperty=hello+from+a+cheeky+user"`?  To even allow overwriting `hasOwnProperty`, you'd have to specify `writable: true`.  Even when you did, the `'hasOwnProperty'` property would be non-enumerable so `Object.keys(parsedParams)` would return an empty array.

I am recommending something like this:
```
/**
 * Safely set a value on a dictionary.  Do *not* trigger special behavior from any setters.  An example of a setter is `Object.prototype.__proto__`
 */
function safeSet(obj, key, value) {
    if(key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
}
```

All that work just to keep `Object.prototype` in the prototype chain, even though any properties might be overwritten by parsed query params.  With `Object.create(null)` or `{__proto__: null}`, you avoid ever giving anyone a false sense of security about calling methods on the returned object.

**Comment by taion** [comment]
I think the current implementation in v3.x is mostly okay. `Object.create(null)` is clearly just the right thing to do, but it's breaking some downstream libraries. I plan to update the ones to which I commit to support `null`-prototype objects, but right now this is causing breakages to users.

**Comment by sindresorhus** [comment]
I reverted that change and did a patch release. Sorry for the trouble. I didn't realize users were dependent on the behavior...

**Comment by taion** [comment]
Thanks! I think it would make a lot of sense to release this as 4.0.0. It looks quite a lot more correct – it just unfortunately happens to be breaking in practice.

**Comment by sindresorhus** [comment]
Actually, the correct solution would be to return a [`Map`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map), but since people use this in the browser it's probably not feasible.

**Comment by cspotcode** [comment]
An equally correct solution is to use defineProperty as explained above.
It's browser compatible and is not a breaking change.  There are also safe
Dictionary libraries that can be used.

**Comment by taion** [comment]
Maps are semantically more correct, but they're a lot less fun to work with than objects, because you can't use destructuring assignment with them.

It's really convenient for me to be able to do

```js
const { foo } = query;
```

when working in ES6+ environments, and it would be an inconvenience to lose that for more proper map semantics.

It looks like the bulk of the breaking issues here came via React Router/history, and we have fixed our code with the null-prototype object handling.

**Comment by cspotcode** [comment]
Fair point, though objects are used as dictionaries often enough that the
semantics should hopefully be obvious to all JS devs.

This also raises another question: which browsers are being supported?
`Map` isn't available in all browsers, but neither are some of the other
built-in methods being used.  Forgive me if this is specified in the readme
and I missed it.

**Comment by taion** [comment]
You're talking about IE8 support, right?

The difference is:
- `Object.create(null)` is handled by es5-sham, which I think many people still supporting IE8 already use
- `Object.prototype.defineProperty` can't really be polyfilled well on IE8 at all
- `Map` has much narrower browser support, so in practice will require more users to bring in a polyfill, or else would require using something like babel-runtime here

**Comment by cspotcode** [comment]
Ok, I didn't remember exactly when those features were added to the various
browsers.

According to my tests, `defineProperty` is unnecessary on IE8 since setting
`__proto__` won't modify the prototype; it's just a normal property.

Agreed that far fewer browsers support `Map` than support methods like
`Object.keys` and `reduce`.

**Comment by taion** [comment]
:+1:

(I can't leave a reaction on the "commit added" message)
