### ISSUE TITLE
Parse error with string start /?

### ISSUE THREAD

**Issue by virutmath** [sindresorhus/query-string#56]
With string start with `/?` like `http://example.com/?page=1`, result return
```
queryString.parse('http://example.com/?page=1');
{ 'http://example.com/?page': '1' }
queryString.parse('/?page=1');
{'/?page':'1'}
```

**Comment by virutmath** [comment]
Maybe I should use `extract` function before parse string:
`queryString.parse(queryString.extract('http://example.com/?page=1'))`;

**Comment by sindresorhus** [comment]
Yes
