### ISSUE TITLE
queryString.stringify sorts the values of the array breaking the app logic

### ISSUE THREAD

**Issue by mrkam** [sindresorhus/query-string#61]
As I do not see an option to reopen https://github.com/sindresorhus/query-string/issues/30 I'm filing this as a new issue. 

Please see my comment there https://github.com/sindresorhus/query-string/issues/30#issuecomment-221124798 which gives an example of why it is important to not sort the values of the array.

**Comment by sindresorhus** [comment]
Sorry, missed that. Agreed. Arrays should not be sorted, but I think the object properties should be. No need for an option. Can just be default. PR welcome :)

**Comment by karanjthakkar** [comment]
@sindresorhus Will this be solved by https://github.com/ppershing/query-string/commit/30bd9c226534e3c51633f91a770a50c08b4db140 or would need it something more?

**Comment by SamVerschueren** [comment]
I believe it does. I think it needs an extra test though.

**Comment by mrkam** [comment]
Great! Thank you!
