### ISSUE TITLE
Upgrade guide or change log

### ISSUE THREAD

**Issue by axelson** [sindresorhus/query-string#72]
Is there an upgrade guide or change log that I'm missing? I'm looking for the steps to upgrade from 3.0.3 to the latest 4.2.2 release.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/query-string/compare/v3.0.3...v4.2.2

The only breaking change is that the returned object is doesn't have a prototype: https://github.com/sindresorhus/query-string/commit/7bebd8e430eb41ed42a749a1dd1d546eeb7fedb5

And yes, I'm aware a changelog would be better, but I honestly don't have the time to maintain one. Happy to add anyone that wants to help out.
