### ISSUE TITLE
Let `stringify` method receive an array of characters to exclude from encoding

### ISSUE THREAD

**Issue by luisincrespo** [sindresorhus/query-string#74]
Not an issue, more of a feature request:

Sometimes I find myself in the need of avoiding the encoding of a certain set of specific characters.

@sindresorhus do you think it'll be useful to add options to the `stringify` method to specify which characters to exclude from encoding? Let me know and I could work on a PR for that.

**Comment by sindresorhus** [comment]
> Sometimes I find myself in the need of avoiding the encoding of a certain set of specific characters.

Why would you do that?

**Comment by luisincrespo** [comment]
For specific use cases, let's say I'd like...

```javascript
{ a: '[b:c]', d: '<>'}
```

To be stringified as `?a=[b:c]&d=%3C%3E` instead of `a=%5Bb%3Ac%5D&d=%3C%3E`

**Comment by sindresorhus** [comment]
Ok, sorry, but I'm not interested in supporting weird cases like that. `?a=[b:c]&d=%3C%3E` makes the URL invalid.
