### ISSUE TITLE
Do not throw an error for malformed URI sequence

### ISSUE THREAD

**Issue by frenzzy** [sindresorhus/query-string#76]
For example such usage will throw an error:
```js
queryString.parse('?%');
queryString.parse('?key=%AF');
queryString.parse('#key%1=value');
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError#Catching_an_URIError

What do you think about adding `try catch` statement?

P.S.: https://github.com/ljharb/qs/blob/master/lib/utils.js#L78-L84

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/query-string/pull/65#issuecomment-225350914.

**Comment by frenzzy** [comment]
There are a lot of misspelled links in the internet.
Do you think it is a good idea to not handle them at all?

Please compare:
- https://www.google.com/?#newwindow=1&q=cats%
- http://www.bing.com/search?q=cats%
