### ISSUE TITLE
base64 in url

### ISSUE THREAD

**Issue by bochen2014** [sindresorhus/query-string#80]
Hi, 
`http://localhost:8000/activate?appl_id=3298&access_key=tYq3O1GMZR+MP6fKvcdobQ/IQfapaw9wV3oa2t5SKxA=`
the access_key is a base64 string, which contains `+` , and it gets replaced by space in source code:
```
	var parts = param.replace(/\+/g, ' ').split('=');
```
why do we need to replace `+` to space? the urlEncoded space is %20 isn't it?

**Comment by sindresorhus** [comment]
You need to encode query parameters.

**Comment by bochen2014** [comment]
`encodeURI('+')` returns `+`

How do you want me to encode?

**Comment by SamVerschueren** [comment]
[encodeURIComponent](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

**Comment by bochen2014** [comment]
got it. thanks!
