### ISSUE TITLE
Array need in the same format with comma separated

### ISSUE THREAD

**Issue by balrajhariharan** [sindresorhus/query-string#86]
Suppose, 
let  path = {
                      pathname : [ 'path1'],
                      direction : ['dir1', 'dir2','dir3'],
                      stops: ['stop1','stop2'],
                   };

queryString.stringify(path);
==>   &path={"pathname":["path1"],"direction":["dir1","dir2","dir3"],"stops":["stop1","stop2"]}

Is this possible.  Thanks.

**Comment by sindresorhus** [comment]
Use JSON: https://github.com/sindresorhus/query-string#nesting
