### ISSUE TITLE
arrayFormat bracket doesn't parse query string as per node.js

### ISSUE THREAD

**Issue by vishalmindtickle** [sindresorhus/query-string#88]
When there's only one value in array, it gives value without wrapped in array.
e.g.: queryString.parse('foo[]=bar', {arrayFormat: 'bracket'}) results in 
{ foo: 'bar' }

but node.js parses same query string in 
{ foo: ['bar'] }

**Comment by sindresorhus** [comment]
// @rapzo

**Comment by rapzo** [comment]
Will look into it.

When you say node.js, do you mean `qs` module? Cause node.js native `querystring` doesn't parse bracketed nor indexed array representation, me thinks.

**Comment by vishalmindtickle** [comment]
@rapzo, oh I am using express (4.14.0), which parses query string in this format, not node.js.

**Comment by rapzo** [comment]
Nice find @vishalmindtickle PR waiting for review. Sorry for the delay, busy weeks...
