### ISSUE TITLE
stringify array as comma separated values

### ISSUE THREAD

**Issue by sashakru** [sindresorhus/query-string#90]
Hello there,

it could very nice to have ability to do something like this : 
```
const obj = {foo: [1,2,3]};
queryString.stringify(obj, {arrayFormat: 'comma'})
```
And the result of this method will be: `foo=1,2,3`.

**Comment by SamVerschueren** [comment]
Why?

**Comment by sashakru** [comment]
Well only one reason I can think about right now that this way is much more compact.

**Comment by SamVerschueren** [comment]
The thing is that every other parser will just parse this as a string. It's not part of the spec for a very good reason. The other end can't know if it was meant as one value or as an array of values. `foo=hello, sam` for instance. What does it mean? Was it meant as aan array? Was it meant just as a string.

**Comment by sashakru** [comment]
Ok, got it, from this point of view it is really make sense.

**Comment by m59peacemaker** [comment]
@sashakru You can use [this query string package](https://github.com/m59peacemaker/js-qs#delimiters) to do that, but as mentioned, it's not common. I've seen it done from time to time. If you're in control of both the client and server, and as long as you support the regular syntax as well so that other clients can submit arrays, and you're sure your delimiter won't conflict with anything, it's probably ok.

**Comment by nsonankar** [comment]
@sashakru:   I am trying to use  queryString.stringify(obj, {arrayFormat: 'comma'})
but for me its not coming properly, here is my object. Please correct what i am missing
qs = {
order_direction: [ 'ASC', 'desc' ]
}
And i am using as 
`${queryString.stringify(qs, { arrayFormat: 'comma' })}`

the output i got is :  [object Object]order_direction=ASC[object Object]order_direction=desc[object Object]

What is missing here?

**Comment by nsonankar** [comment]
Hello,

const obj = {foo: [1,2,3]};
// queryString.stringify(obj, {arrayFormat: 'comma'})
QueryString doesn't supporting arrayFormat: 'comma',
To get this result, foo=1,2,3.
we can use .join method of javascript.
 **like: foo.join();**
And the result of this method will be: **foo=1,2,3.**

**Comment by SamVerschueren** [comment]
@nsonankar I answered it in https://github.com/sindresorhus/query-string/issues/90#issuecomment-292970631 why it doesn't make sense to support this.
