### ISSUE TITLE
Support to object tree

### ISSUE THREAD

**Issue by maxviewup** [sindresorhus/query-string#93]
The module doesn't support object tree. Example:
```
var foo = {
    filter: {
        brand: [
            'a',
            'b'
            ]
    },
    size: 42
};
queryString.stringify(foo);
```

should generate 
`filter%5Bbrand%5D%5B0%5D=a&filter%5Bbrand%5D%5B1%5D=b&size=42` 
or 
`filter[brand][0]=a&filter[brand][1]=b&size=42`

but the output was
`filter=%5Bobject%20Object%5D&size=42` or `filter=[object Object]&size=42`

I need something that can parse anything to queryString, like PHP's `http_build_query` and `parse_str`

**Comment by sindresorhus** [comment]
It intentionally doesn't support nesting, as it's both hard to do right and comes with many edge-cases and potential security problems. See https://github.com/sindresorhus/query-string#nesting or use https://github.com/ljharb/qs instead.

**Comment by maxviewup** [comment]
Thanks for the fast feedback
