### ISSUE TITLE
Query parse misbehaving, leading ? is not ignored

### ISSUE THREAD

**Issue by L3V147H4N** [sindresorhus/query-string#94]
Using `"query-string": "^4.3.4"`

`queryString.parse('?intended=sign-in)` returns

```JS
{
  "?intended": "sign-in"
}
```

**Comment by sindresorhus** [comment]
We have a test proving it works: https://github.com/sindresorhus/query-string/blob/27e4fae3e79d179bcf79c32cf3bb404770ac0491/test/parse.js#L5

**Comment by L3V147H4N** [comment]
Sorry, I just checked the code:

Turns out I was actually importing `from 'queryString'` and it seems it was a valid module within my project so there were no importing errors.

I changed it to `'query-string'` and now it works
