### ISSUE TITLE
q

### ISSUE THREAD

**Issue by jihin** [sindresorhus/query-string#95]
stringify not working correctly,

When I am trying to stringify my object getting this
`queryString.stringify({foo: [1,2,3]}, {arrayFormat: 'bracket'});`
 getting output `foo=1[object Object]foo=2[object Object]foo=3`
expected out put `foo[]=1&foo[]=2&foo[]=3 `

**Comment by sindresorhus** [comment]
You're probably using the Node.js query string module instead of this one. Before opening an issue, always look at the test to confirm whether it's your fault or the module.
