### ISSUE TITLE
Should handle querystrings in case-insensitive manner

### ISSUE THREAD

**Issue by buddyackerman** [sindresorhus/query-string#96]
You never know if a user or some other system is going to provide a querystring parameter in the same case that you expect.  There should be an option that allows you to specify case insensitive handling and if this option is on (in fact it should be the default) then all querystring parameters come in as lowercase (properties or key names)

e.g

`
    http;//www.my.website.com/somepage.html?QuerYpaRam1=somevalue
`

Result

`
    {
        queryparam1: somevalue
    }
`

**Comment by sindresorhus** [comment]
I disagree and none of the other querystring implementations do this either.

I want to follow [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) as much as possible:

```js
x = new URLSearchParams('FOO=1&foo=2');
console.log(Array.from(x.keys()));
//=> ["FOO", "foo"]
```

**Comment by sindresorhus** [comment]
> You never know if a user or some other system is going to provide a querystring parameter in the same case that you expect.

https://github.com/sindresorhus/lowercase-keys

**Comment by buddyackerman** [comment]
I'll disagree with your disagreement.  That no other implementations don't do it is a poor argument.  This could be made part of the options object passed to the parse function.  If you don't want it to be the default, fine but it should be an options.  It's obvious that querystring parameters are not case sensitive and any querystring parser should handle them as such.

Anyway, I've change my local version to this



    return Object.keys(ret).sort().reduce(function (result, key) {
        var val = ret[key];

        //Lowercase the key
        key = key.toLowerCase();

        if (Boolean(val) && typeof val === 'object' && !Array.isArray(val)) {
            // Sort object keys, not values
            result[key] = keysSorter(val);
        } else {
            result[key] = val;
        }

        return result;
    }, Object.create(null));
