### ISSUE TITLE
URIError: malformed URI sequence

### ISSUE THREAD

**Issue by ogarich89** [sindresorhus/query-string#98]
When you reload a page with a URL having the form '?q=%'  an error occurs **URIError: malformed URI sequence** 

Solution: 

`        try {
            val = val === undefined ? null : decodeURIComponent(val);
        } catch (e) {
            val = null;
        }`

Is it correct?

**Comment by SamVerschueren** [comment]
See the discussion at #97

**Comment by ogarich89** [comment]
Thanks

**Comment by SamVerschueren** [comment]
Fixed in `5.0.0`.
